### ISSUE TITLE
Linking error when running stdweb::initialize().

### ISSUE THREAD

**Issue by sanatshah** [koute/stdweb#101]
Probably a simple error, I'm trying to use stdweb with:

`extern crate stdweb;

pub fn main() {
        stdweb::initialize();
}
 `

I end up getting the error : 
`error: linking with `cc` failed: exit code: 1 ......
  
  = note: Undefined symbols for architecture x86_64:
            "_emscripten_asm_const_int", referenced from:
                stdweb::webcore::initialization::initialize::h4c8e9303822f5ec1 in libstdweb-310da87d7f95429a.rlib(stdweb-310da87d7f95429a.stdweb4.rust-cgu.o)
                stdweb::webcore::initialization::initialize::_$u7b$$u7b$closure$u7d$$u7d$::h292eb6004a949697 in libstdweb-310da87d7f95429a.rlib(stdweb-310da87d7f95429a.stdweb4.rust-cgu.o)
                _$LT$stdweb..webcore..value..Reference$u20$as$u20$core..ops..drop..Drop$GT$::drop::h41b8da88f774e14b in libstdweb-310da87d7f95429a.rlib(stdweb-310da87d7f95429a.stdweb0.rust-cgu.o)
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

I have installed x86_64-apple-darwin on a 64-bit MacOS. New to rust, any help will be appreciated. 

Thanks

**Comment by koute** [comment]
Are you compiling it directly with `cargo` by any chance? You need to add `--target=asmjs-unknown-emscripten` or `--target=wasm32-unknown-emscripten` parameter for that to work. However, those two targets require [Emscripten](https://kripken.github.io/emscripten-site/docs/getting_started/downloads.html) to be installed.

You can also try the `--target=wasm32-unknown-unknown` target, which doesn't require Emscripten, but you need to build through [`cargo-web`](https://github.com/koute/cargo-web/) for it to work. (Even *if* you're compiling for one of the `*-emscripten` targets I would recommend using `cargo-web` anyway.)

If you have any further questions feel free to ask!

**Comment by sanatshah** [comment]
Yep that was it, thank you!
