### ISSUE TITLE
std::js_export causing "cargo check" to fail

### ISSUE THREAD

**Issue by bgourlie** [koute/stdweb#106]
I use `cargo check` often (as does the IntelliJ rust plugin) to verify the correctness of my rust code without having to do a full `cargo web` build. I recently started using the `js_export` procedural macro, and something about it causes `cargo check` to fail even though it compiles fine using `cargo web`.

**Comment by koute** [comment]
1. Are you adding `--target=wasm32-unknown-unknown` argument to `cargo check`?
2. If you are then could you paste any errors you're getting? (Since `cargo check` works for me.)

**Comment by bgourlie** [comment]
That fixed it, much appreciated. I'll file a bug with the intellij plugin team to see how it can accommodate these flags when using `cargo check` for on-the-fly error reporting.
