### ISSUE TITLE
Missing Symbol variant in Value

### ISSUE THREAD

**Issue by Pauan** [koute/stdweb#115]
According to [the ECMAScript spec](https://www.ecma-international.org/ecma-262/6.0/#sec-ecmascript-language-types) the JavaScript types are Undefined, Null, Boolean, String, Symbol, Number, and Object. We have every one of them except Symbol.

You can check if something is a Symbol by using `typeof foo === "symbol"`

**Comment by koute** [comment]
Yep. That's something I planned to do anyway. Thanks for reminding me.

**Comment by koute** [comment]
I've added initial implementation of `Symbol` and I've added it as a variant to `Value`. For now you can't really do much with it besides passing it in-and-out of `js!`, but it's a start.
