### ISSUE TITLE
Feature request: imlement trait `TryFrom<usize>` for `stdweb::Value`

### ISSUE THREAD

**Issue by Shnatsel** [koute/stdweb#12]
Just what it says on the tin. It's weird that `TryFrom<u64>` is implemented for `stdweb::Value` but `TryFrom<usize>` is not.

Use case: I was trying to pass two arrays of integers into JS, iterate over them to do some lookup based on both and call functions with side effects on the result of lookup. I came up with the following code:

```
    let array_a: stdweb::Value = vec_a.into();
    let array_b: stdweb::Value = vec_b.into();
    js! {
        var lookup_result = [];
        var length = @{array_a}.length;
        for (var i = 0; i < ; i++) {
            lookup_result.push(lookup_a(@{array_a}[i]).lookup_b(@{array_b}[i]));
        }
        func_with_side_effects(lookup_result)
    };
```

But Rust complained that array_a is moved at length lookup and I cannot use it again. So I've tried adding length and passing it to JS explicitly:

`let length: stdweb::Value = position_hashes.len().try_into().unwrap();`

but that complained that "the trait `stdweb::unstable::TryFrom<usize>` is not implemented for `stdweb::Value`"

**Comment by koute** [comment]
Done!

Thanks for the well written issue!
