### ISSUE TITLE
RFC: Export hierarchy

### ISSUE THREAD

**Issue by JustinRyanH** [koute/stdweb#123]
Need
-----
I have a desire to replace standard javascript code with Rust WebAssembly for javascript libraries. However I notice there isn't currently a good way to get an hierarchy of methods when exporting into a javascript structure without using multiple. I would like to be able to group up certain methods by type. However I think it would be beneficial to replicate the `module` structure from Rust into a object Hierarchy, as explained in the proposal.

Proposal
---- 
Replicate the `module` structure into the exported javascript Object.

Given the following Rust code:

``` rust
mod foobar {
  #[js_export]
  pub fn biz() {} 
}

mod another_mod {
  #[js_export]
  pub fn another_function() {}
}

#[js_export]
pub fn important_function() {}
```

The Result

``` javascript
{
   important_function: [Function: function],
   foobar: { 
     biz: [Function: function],
   },
   another_mod: {
      another_function: [Function: function],
   },
}
```

Proposal on how to Develop This
------

I will take on the effort to develop this, but however I want to take a few steps to get it resolved in a clean and predictable manor.

- [ ] Create a argument to declare the module the export belongs in
- [ ] Create a module to resolve the Proposal solution 
- [ ] Create documentation in README.md

**Comment by koute** [comment]
Hm... I don't think that it's possible to do this the way you've envisioned. Rust's procedural macros (AFAIK) don't know in which scoped they're used.

However, something like this should be feasible:

```rust
#[js_export(module="foo")
fn bar() {}
```

Also, we *do* have some integration tests for the `js_export` in the `standalone-tests` directory.

**Comment by JustinRyanH** [comment]
Oh cool. Thanks for the info with the Integration tests.

**Comment by JustinRyanH** [comment]
Also that would be a perfect intermediate step regardless of the solution. So I think I'll add that to my proposal and steps. In fact I bed I can get that together first.

**Comment by koute** [comment]
Also, one more thing - I generally prefer integration tests to unit tests in cases like these, which is why there are no unit tests for `js_export`. With enough integration tests you often can get exactly the same coverage but without having to tie your tests closely to your code (which makes it hard/annoying to refactor later). So if you're going to add extra tests (which I would be very happy to have!) please first consider whenever it's possible to test the functionality through an integration test. (:

**Comment by JustinRyanH** [comment]
Understood. I definitely feel integration and acceptance test are way more important than Unit Testing, but I often end up creating Unit Test to understand how the internal code works, and hopefully help explain future developers how the tests work. 

Also I added a new step to the RFC

**Comment by koute** [comment]
Sounds good to me, so if you feel like taking a stab at this then be my guest. (:
