### ISSUE TITLE
RFC: Dealing with mixins as defined in the specs

### ISSUE THREAD

**Issue by koute** [koute/stdweb#124]
So in preperation for [releasing `0.4`](https://github.com/koute/stdweb/issues/75) I've been going through all of our API bindings, adding links to the specs everywhere and tweaking the APIs to be compliant with them.

I got to the `query_selector` and `query_selector_all` methods, which we originally had defined as (duplicate) `impl`s of `Document` and `IElement`. I've opened [the specs](https://dom.spec.whatwg.org/#parentnode) and saw that they're supposed to be defined in a mixin called `ParentNode`, so I removed those methods from `Document` and `IElement`, and redefined them in a `IParentNode` trait. (We already had one such mixin interface - `IWindowOrWorker`.)

So, before we had something like this:

```rust
impl Document {
    ...
    fn query_selector( ... ) -> ... { ... }
    ...
}
```

and now we have this:

```rust
impl Document {
    ...
}
pub trait IParentNode: ReferenceType {
    fn query_selector( ... ) -> ... { ... }
}
impl IParentNode for Document {}
```

The main downside of this is that it's somewhat non-intuitive and that now the user has to import an extra trait to be able to use `query_selector`, e.g.:

```rust
use stdweb::web::document;
use stdweb::web::IParentNode; // <- This wasn't necessary before.

let _ = document.query_selector( ... );
```

So, now, I've got to yet *another* method which is like that - `get_element_by_id`, defined in the [`NonElementParentNode` mixin](https://dom.spec.whatwg.org/#interface-nonelementparentnode), and it dawned on me - *is there any point in doing this*?

The `get_element_by_id` method is one of **the** most commonly used methods of all Web APIs. On the other hand **no one** cares that it's *technically* defined in a mixin. The mixins themselves have (as far as I can tell) no real practical significance as they're **not** normal JS interfaces (e.g. you can't check that `x instanceof MixinType` in JS), and they exist only "virtually" as a way to categorize various APIs from the specs' point of view.

So, we have two alternatives:
1. Create an interface for every mixin in the specs. The specs has a lot of them, e.g. `NonElementParentNode`, `DocumentOrShadowRoot`, `ParentNode`, `NonDocumentTypeChildNode`, `ChildNode`, `Slotable`, etc. This is more true to the specs, but is annoying from the user's point of view due to having to import extra traits and being non-obvious, while having (I think) little practical benefits.
2. Inline the respecive methods from the respective mixins into concrete Web APIs. (e.g. define two `query_selector` methods - in `Document` and in `IElement`.) This is not how the specs define those APIs, but then we won't have a bunch of useless traits lying around. We'll have some extra code duplication though.

So, since I'm in a little bind as to what do here I want to ask you - what do you think? Which option do you prefer? Do you see any benefits to having those mixin-traits defined?

(ping @Diggsey @Pauan @Herschel @DenisKolodin @emk @jdanford - if any of you have any input and feel like sharing I'd appreciate it; if I didn't mention you then I'd appreciate your input all the same)

**Comment by Diggsey** [comment]
How about we use traits as we do currently but we provide one or more
"prelude" modules from which all the helper traits can be imported in one
go?

**Comment by Pauan** [comment]
How about a third option:

3. For every method which exists on multiple concrete types (such as `query_selector`), create a trait. But it shouldn't be constrained at all by the spec, so we can choose a Rusty name for it, and we can slice-and-dice it as much as we want.

   For example, we might decide to have one method per trait, or combine multiple methods into a single trait, however we feel is best.

@Diggsey I like that idea. Perhaps something like `use stdweb::web::traits::*` or even `use stdweb::traits::*`

**Comment by koute** [comment]
@Diggsey That's something that I though about too, and, well, it's certainly a feasible workaround for the import issue.

However, I'm still feeling pretty ambivalent about this (I don't really like any of the options), which is why I decided to ask the community what they prefer.

**Comment by Pauan** [comment]
For the specific situation of `query_selector` we could have an `IQuerySelector` trait which is then required by both `IDocument` and `IElement`:

```
trait IQuerySelector: ReferenceType {
    // ...
}

trait IDocument: IQuerySelector + INode {}
trait IElement: IQuerySelector + INode {}
```

This also mimics how the spec treats `querySelector` as a "mixin" and not a true interface.

**Comment by Diggsey** [comment]
You may be interested in this RFC I've had open for a while:
github.com/rust-lang/rfcs/pull/2309

This would allow us to proceed with the prelude solution now and then
switch to inherent trait implementations later assuming it is accepted in
some form.

**Comment by Pauan** [comment]
@Diggsey Why don't we do that right now? I mean, write a macro which will create concrete implementations for the types. That way we can use traits internally to avoid code duplication, but the public API will be concrete methods.

**Comment by DenisKolodin** [comment]
I think the first (create an interface for every mixin in the specs) is simpler for tracking.
I'm ok about importing many traits. If I will need to reduce imports I can use or create own `prelude` workaround.

**Comment by Diggsey** [comment]
@Pauan you *could* but it would be quite invasive right now: the macro needs to know about all the methods on the trait so either you declare a macro for each trait that implements its methods for a type, or you make a single macro that takes an entire trait declaration as input, and a set of types to implement it for and the generates all of the required inherent methods.

**Comment by emk** [comment]
I haven't taken the time to understand all the issues, but I suspect that abstract interfaces in the spec can also be useful in real code. If two types are defined as supporting the same `query` function in the spec, it's likely that some Rust code might want to access any type that implements that interface.

But I'm far too tired right now to exercise good design judgement so take this with a grain of salt please. :-)

**Comment by Pauan** [comment]
Another possibility:

4. Create regular private `fn`s for the behavior, and then delegate to them:

   ```rust
   fn query_selector( ref: Reference, selector: &str ) -> Result< Option< Element >, UnimplementedException > {
       // ...
   }

   impl Document {
       #[inline]
       fn query_selector( &self, selector: &str ) -> Result< Option< Element >, UnimplementedException > {
           query_selector( self.0, selector )
       }
   }
   ```

----

Personally, I think using traits is fine, as long as we have a `stdweb::traits` module that the user can easily import to get all the traits. Although the spec names are unusual, using traits *is* the Rust-y way to do things.

**Comment by Herschel** [comment]
I think traits are the easiest way forward for all of the reasons outlined above.

`ParentNode` makes sense as a trait because there is a fairly big interface baked in there. In general, though, I don't think we have to follow the specs/API verbatim. (e.g. do we really need `INonDocumentTypeChildNode`, could we instead just ditch that mixin and have `nextElementSibling` just return `None` for a `DocumentType` node?). But just following the spec is definitely the path of least resistance, and I don't think it would bother anyone too much.

It is more annoying to import traits from a user point of view, but I think this is par for the course in Rust, and rustc gives very good error messages regarding this. A prelude would definitely help, and then it's mostly an issue of documentation to hint users about it.

**Comment by koute** [comment]
Thanks for the input everyone!

I'll go with the prelude for now.
