### ISSUE TITLE
Async unit tests

### ISSUE THREAD

**Issue by Pauan** [koute/stdweb#128]
Since we now have *excellent* Promise and Future support, we should start thinking about how to write async unit tests.

@koute you said you had some ideas about this, what are they?

**Comment by koute** [comment]
Yes, well, it shouldn't be *super* hard to get async tests working today, it'd just involve quite a bit of legwork.

The biggest issue currently with having async tests is that Rust itself doesn't support custom test harnesses, so we'd have to get around that.

Something like this:

1) Write a procedural attribute macro, in a fashion similar to the current `#[js_export]` - call it `#[async_test]` or something like that. For every function marked with it something like this would be generated: (would require #![feature(linkage)])

```rust
#[linkage = "external"]
#[no_mangle]
#[allow(dead_code)]
extern fn test_foobar() {
    // ...
}
```

Then you could just slap an `#[async_test]` anywhere you want in your project just as you'd do with `#[test]`.

2) When compiling tests have `cargo-web` extract all of the async tests, generate a custom test harness for it and then run them.

I don't think we should involve promises and futures into this though, at least on the lowest level; having `fn test_foobar(done: fn())` would be enough (then you could test promises and futures themselves like this, and most of our async APIs don't need full power of promises/futures to test them anyway)

**Comment by Diggsey** [comment]
> I don't think we should involve promises and futures into this though

I disagree on the futures point - I think we should push towards ubiquitous use of futures and streams for async programming within stdweb - I imagine we'll get *some* form of `await` usable on stable this year, and I'd like to be able to take full advantage of that with stdweb.

I want to be able to slap `#[async_test]` directly on an async function and have it behave as expected. I think we should even push for this async test harness to be supported upstream of stdweb, and I think there will be wide support for this amongst all rust users.

The way I see it, stdweb should be the gateway between the javascript/browser/node world and the rust world, providing interfaces and compatibility layers where appropriate, but on the rust side of that boundary we should have "normal" rust code, where the best practices for rust on stdweb are the same as the best practices for any rust project.

**Comment by Pauan** [comment]
> @koute I don't think we should involve promises and futures into this though, at least on the lowest level

I agree that the lowest level should be very simple, but testing Futures will be *very* common, so we need some sugar on top which makes it easy.

Perhaps something like this:

```rust
#[async_callback_test]
fn foo(done: fn()) {
    // ...
}

#[async_future_test]
fn foo() -> impl Future<Item = (), Error = Error> {
    // ...
}
```

**Comment by koute** [comment]
@Diggsey I think you've misunderstood me. (: 

We should definitely support promises in async tests for user code! What I'm saying is that:

  1) the very basic mechanism of async tests should *not* depend on futures, and that it should be possible to write async tests without requiring futures,
  2) async tests in `stdweb` itself should not use futures - I'd like to keep the `futures` feature optional, and I don't think we actually *need* the power of futures anywhere.

@Pauan I don't think two attributes are necessary; the procedural attribute macro has access to the function's signature, so it can figure out which type of test to generate based on that (although, as I've said - the future based tests should be implemented on top of `done: fn()` ones, so the generated code would be *mostly* the same, with the difference that the futures one would desugar to the `done: fn()` one)

**Comment by koute** [comment]
Also, one more thing - it'd be nice to have access to `#[linkage = "external"]` on stable (to have the ability to export functions from anywhere, not only from `lib.rs` or `main.rs`), and I don't believe that it's possible to do that in any other way except `#![feature(linkage)]`. Sooner or later I'll probably whip up an RFC with a proposal to stabilize this functionality in some way.

**Comment by Pauan** [comment]
@koute Yup, we're in agreement: futures should desugar to `done: fn()`, and you make a good point about being able to dispatch based on the return type, I like it.

**Comment by Pauan** [comment]
Also, I'm currently busy with some other things, so I won't be able to tackle this anytime soon, I just wanted to get the ball rolling, since I think this is a very important issue for stdweb (both within stdweb and also for users of stdweb).

**Comment by koute** [comment]
I've just added experimental support for async tests to `cargo-web`. (It works across every `--target`, both under node.js and under headless Chromium.) I'll push a procedural attribute macro soon to `stdweb`.

**Comment by koute** [comment]
And the `#[async_test]` procedural macro is here.

Example test: (not yet commited since I want to possibly refactor the `Promise` while I'm at it)

```rust
#[cfg(all(test, rust_1_30_or_newer, rust_nightly))]
mod async_tests {
    use super::*;
    use webapi::global::set_timeout;
    use async_test;

    fn new_promise() -> Promise {
        js!(
            var resolve_fn;
            var reject_fn;
            var promise = new Promise( function( resolve, reject ) {
                resolve_fn = resolve;
                reject_fn = reject;
            });
            promise.call_resolve = resolve_fn;
            promise.call_reject = reject_fn;

            return promise;
        ).try_into().unwrap()
    }

    #[async_test]
    fn test_promise_done< F: FnOnce( Result< (), String > ) >( done: F ) {
        let promise = new_promise();
        promise.done( |result: Result< i32, () >| {
            match result {
                Ok( 123 ) => done( Ok(()) ),
                result => done( Err( format!( "unexpected value: {:?}", result ) ) )
            }
        }).leak();

        set_timeout( || {
            js!( @{promise}.call_resolve( 123 ); );
        }, 0 );
    }
}
```
