### ISSUE TITLE
Setting callback for async functions

### ISSUE THREAD

**Issue by afshinm** [koute/stdweb#13]
I'm trying to use `fetch` to load a file and then call a closure on the Rust side, like this:

    let call_fn = |txt: String| {
        println!( "{}", txt );
    };

    js! {
        var call_fn = @{call_fn};
        fetch( "/test.csv" ).then((res) => res.text()).then(call_fn);
    }

But I'm getting this error:

> Panic error message: cannot access stdout during shutdown

Any chance to make it work?

**Comment by koute** [comment]
Did you call `stdweb::event_loop` at the end of your `main` function?

**Comment by afshinm** [comment]
yeah I did

**Comment by afshinm** [comment]
Ow, my fault. Actually there was a runtime error in my app so looks like it was preventing the callback to be accessible. 

Thanks @koute
