### ISSUE TITLE
thread 'main' panicked at 'unsupported custom section: 'sourceMappingURL'', src/wasm_context.rs:623:25

### ISSUE THREAD

**Issue by Unmoving** [koute/stdweb#131]
I did a `cargo update` and then run `cargo web build` as usual. Leads to:

> thread 'main' panicked at 'unsupported custom section: 'sourceMappingURL'', src/wasm_context.rs:623:25
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:68
             at libstd/sys_common/backtrace.rs:57
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:381
   3: std::panicking::default_hook
             at libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:522
   7: cargo_web::wasm_context::Context::from_module
   8: cargo_web::wasm::process_wasm_file
   9: cargo_web::cargo_shim::BuildConfig::build_internal
  10: cargo_web::cargo_shim::BuildConfig::build
  11: cargo_web::cmd_build::command_build
  12: cargo_web::main
  13: std::rt::lang_start::{{closure}}
  14: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:480
  15: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  16: std::rt::lang_start_internal
             at libstd/panicking.rs:459
             at libstd/panic.rs:365
             at libstd/rt.rs:58
  17: main
  18: __libc_start_main
  19: _start

``` 
#[macro_use]
extern crate stdweb;

use stdweb::unstable::TryInto;
use std::rc::Rc;

use stdweb::web::{
    INode,
    HtmlElement,
    IEventTarget,
    WebSocket,
    document,
    IParentNode,
};

use stdweb::web::html_element::InputElement;

use stdweb::web::event::{
    IEvent,
    IKeyboardEvent,
    IMessageEvent,
    SocketOpenEvent,
    SocketCloseEvent,
    SocketErrorEvent,
    SocketMessageEvent,
    KeyPressEvent,
};

fn log(msg: &str) {
    js! {@(no_return)
        console.log(@{msg});
    }
}


// Shamelessly stolen from webplatform's TodoMVC example.
macro_rules! enclose {
    ( ($( $x:ident ),*) $y:expr ) => {
        {
            $(let $x = $x.clone();)*
            $y
        }
    };
}


fn main() {
    stdweb::initialize();
    ws_test();
    stdweb::event_loop();
}

fn ws_test() {
    let output_div: HtmlElement = document().query_selector(".output").unwrap().unwrap().try_into().unwrap();
    let output_msg = Rc::new(move |msg: &str| {
        let elem = document().create_element("p").unwrap();
        elem.set_text_content(msg);
        if let Some(child) = output_div.first_child() {
            output_div.insert_before(&elem, &child);
        } else {
            output_div.append_child(&elem);
        }
    });

    output_msg("> Connecting...");

    let ws = WebSocket::new("ws://localhost:8000/api/ws").unwrap();
    ws.add_event_listener(enclose!( (output_msg) move |_: SocketOpenEvent| {
        log("> Opened connection");
        output_msg("> Opened connection")
    }));

    ws.add_event_listener(enclose!( (output_msg) move |_: SocketErrorEvent| {
        log("> Connection had error");
        output_msg("> Connection had error")
    }));

    ws.add_event_listener(enclose!( (output_msg) move |event: SocketCloseEvent| {
        log(&format!("> Connection Closed: {}", event.reason()));
        output_msg(&format!("> Connection Closed: {}", event.reason()));
     }));

    ws.add_event_listener(enclose!( (output_msg) move |event: SocketMessageEvent| {
        log(&event.data().into_text().unwrap());
        output_msg(&event.data().into_text().unwrap());
    }));

    let text_entry: InputElement = document().query_selector(".form input").unwrap().unwrap().try_into().unwrap();
    text_entry.add_event_listener(enclose!( (text_entry) move |event: KeyPressEvent| {
         if event.key() == "Enter" {
             event.prevent_default();

             let text: String = text_entry.raw_value();
             if text.is_empty() == false {
                 text_entry.set_raw_value("");
                 ws.send_text(&text);
             }
         }
     }));
}
```

**Comment by koute** [comment]
This is due to recent changes on nightly Rust; you need to update your `cargo-web` and it will work again.

**Comment by Unmoving** [comment]
How embarrassing. Thanks!
