### ISSUE TITLE
"signature does not match" on mobile Safari with wasm32-unknown-unknown

### ISSUE THREAD

**Issue by skade** [koute/stdweb#134]
I receive the following error when trying to trigger a callback on mobile Safari.

```
Error: call_indirect to a signature that does not match (evaluating 'Module.web_table.get( ptr ).apply( null, args )')
```

Rust code:

```

fn main() {
    stdweb::initialize();

    let register_hits_button: Element = document().query_selector( ".press" ).unwrap().unwrap();
    register_hits_button.add_event_listener(move |_: ClickEvent| {
       console!(log, "worked!");
    });

    stdweb::event_loop();
}
```

A full example can be found here https://github.com/skade/safari-sample

For easy testing: https://skade.github.io/safari-sample/

Press the button to see the problem.

**Comment by Pauan** [comment]
Hmmm, that sounds like a problem with either Rust's generation of wasm, or Safari's implementation of wasm.

Since it works fine in other browsers, and since wasm is still relatively new, I'm *guessing* it's a bug in Safari.

**Comment by skade** [comment]
Well, I got as much, is there any good path to debug that?

I'd be willing to help out, but I don't have a good idea on where to start and I also don't know what the wasm-runtime does exaclty.

**Comment by Pauan** [comment]
@skade Unfortunately I don't have any experience with mobile, so I can't help you. But maybe somebody else can.

**Comment by koute** [comment]
@skade Hmm... well, I'd start by grabbing the generated `.wasm` and `.js` and try to cut it down as much as I can, and then try to reproduce the issue manually to see *why* it happens. Once we know the reason we might be able to envision a workaround of some sort.

**Comment by skade** [comment]
I bit the bullet and updated to iOS 11.3 beta and can confirm that it works now.

I'd keep the issue open until iOS 11.3 is properly released, recheck and close. @koute, can you assign me?

**Comment by koute** [comment]
@skade Thanks for the update!

**Comment by skade** [comment]
Confirmed that it works with iOS 11.3 stable. Closing.
