### ISSUE TITLE
[Question] How can I pass a tuple in js_export function?

### ISSUE THREAD

**Issue by y-ich** [koute/stdweb#136]
Hi.

I want to pass a combination of two different types to JS, like the below.

```rust
#[js_export]
fn example() -> (usize, f64) {...}
```

Since stdweb seems not to support Rust's tuple, I have no idea to compile this code.
How can I do it?

Thank you.

**Comment by koute** [comment]
Yes, tuples are currently not supported.

You can either return a structure with those two fields (use our `serde` integration), or return something like `Vec<Value>`.

**Comment by y-ich** [comment]
Thank you!
I certainly looked at an example of serde in README.md, but I could not remember it.
