### ISSUE TITLE
Document the WebAssembly story

### ISSUE THREAD

**Issue by dgriffen** [koute/stdweb#14]
As far as I can tell this library currently does not support wasm. But since Rust now supports wasm on stable it would be useful if documentation existed somewhere detailing this libraries future plans for supporting wasm, ~~or if it already does and I missed that, there should be docs on how to use this library with wasm.~~

Edit: After fiddling a bit, I have determined that at the very least the todomvc example can run under wasm. This just means that it is unclear if wasm is actually supported or if this is something that is not guarenteed to work going forward.

**Comment by lilianmoraru** [comment]
I managed to make a basic example work, but not `todomvc`:
```
$ wargo build --release
$ cp target/wasm32-unknown-emscripten/release/deps/todomvc-*.{js,wasm} static/  # Hacky, I know :)
$ mv static/todomvc-*.js static/todomvc.js
$ mv static/todomvc-*.wasm static/todomvc.wasm
```

Then I modified `<script src="js/app.js"></script>` into([inspiration](https://www.hellorust.com/emscripten/demos/06-wasm-in-html/)):
```js
<script type='text/javascript'>
	var Module = {};

	fetch('todomvc.wasm').then(response =>
		response.arrayBuffer()
		).then(buffer => {

		Module.wasmBinary = buffer;

		var script = document.createElement('script');
		script.src = "todomvc.js";
		script.onload = function() {
		console.log("Emscripten boilerplate loaded.")
		}
		document.body.appendChild(script);
	});
</script>
```

This basic page would work then:
```html
<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>stdweb • Alert</title>
	</head>
	<body>
		<input class="the-input">
		<script type='text/javascript'>
			var Module = {};

			fetch('todomvc.wasm').then(response =>
				response.arrayBuffer()
				).then(buffer => {

				Module.wasmBinary = buffer;

				var script = document.createElement('script');
				script.src = "todomvc.js";
				script.onload = function() {
				console.log("Emscripten boilerplate loaded.")
				}
				document.body.appendChild(script);
			});
		</script>
	</body>
</html>

```

For this code(did not plan initially  to post the code: at this point I realise I should better push the code somewhere instead of creating a big comment, but this is the last part):
```rust
fn main() {
    stdweb::initialize();

    let state = window().local_storage().get("state").and_then(|state_json| {
        serde_json::from_str(state_json.as_str()).ok()
    }).unwrap_or_else(State::new);

    let state = Rc::new(RefCell::new(state));

    let message: InputElement = document().query_selector(".the-input").unwrap().try_into().unwrap();
    message.add_event_listener(enclose!( (state, message) move |event: KeypressEvent| {
        if event.key() == "Enter" {
            event.prevent_default();

            let msg: String = message.value().try_into().unwrap();
            js! {
                alert( @{msg} );
            }
        }
    }));

    stdweb::event_loop();
}
```

**Comment by lilianmoraru** [comment]
I created a basic example of stdweb + wasm32: https://github.com/lilianmoraru/stdweb-alert-example

I did something wrong or the support is not great(stdweb or/and Rust + emscripten) but while trying to make `todomvc` to work, I had all kinds of missing symbols issues or things like that(even with the basic example sometimes - weird)...

**Comment by koute** [comment]
> I created a basic example of stdweb + wasm32: https://github.com/lilianmoraru/stdweb-alert-example

> I did something wrong or the support is not great(stdweb or/and Rust + emscripten) but while trying to make todomvc to work, I had all kinds of missing symbols issues or things like that(even with the basic example sometimes - weird)...

@lilianmoraru Yes, the way you're using it isn't really supported (yet).

Basically, Rust's Emscripten-based wasm target requires a hefty runtime which you can find in the `.js` file generated alongside the `.wasm`. That `.js` file already includes the code necessary to load the `.js` file, so right now you're supposed to just load that `.js` and it will fetch the `.wasm` by itself, not the other way around.

Rust **is** going to have a native wasm target where it'll only generate a standalone `.wasm` file; I'll add support for that (to both `stdweb` and `cargo-web`) once I'll be able to download a reasonably working toolchain through `rustup`.

**Comment by koute** [comment]
*Currently* it might not be, but I see no reason why we wouldn't be able to work something out. (I'll add it myself if I have to.)

**Comment by emosenkis** [comment]
I believe that wasm32-unknown-unknown is now available from rustup on nightly.

**Comment by lilianmoraru** [comment]
@emosenkis stweb wasm32-unknown-unknown does not currently work with it because it requires an event loop that is available only inside the emscripten environment.
wasm32-unknown-unknown is pretty basic right now, the std is mostly stubbed because compared to emscripten which offers File IO API for example(in RAM), this environment is basic, just wasm32.
If you want a crate to work under this target, the safest way is to not require std.

**Comment by koute** [comment]
Since WebAssembly is now supported on every target that Rust supports - closing!
