### ISSUE TITLE
Should set_timeout require Send?

### ISSUE THREAD

**Issue by negamartin** [koute/stdweb#146]
I'm not sure how this works at all but I think set_timeout might require Send as a constraint on the callback. Could somebody who knows better confirm?

**Comment by CryZe** [comment]
JavaScript and WebAssembly are single threaded at the moment, so there‘s no need for a Send bound. However eventually at least WebAssembly might have some form of threading, so eventually it should have a Send bound.

**Comment by negamartin** [comment]
Ah, I see. There's no problem then, thanks!
