### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by kuviman** [koute/stdweb#148]
Looks like there is a bug in refcounting `Reference`s to JS objects

refcount is [initially set to 1](https://github.com/koute/stdweb/blob/85f7aa484f3be9808b992b9258bd85fa588e05b1/src/webcore/runtime.js#L308), and incremented [when constructing](https://github.com/koute/stdweb/blob/573c7ce5894087c81170bd1eca2a4a5ead8f2d15/src/webcore/value.rs#L33) a `Reference`, but only decremented once [while dropping](https://github.com/koute/stdweb/blob/573c7ce5894087c81170bd1eca2a4a5ead8f2d15/src/webcore/value.rs#L83) the `Reference`

This code leaves `Module.STDWEB_PRIVATE.id_to_refcount_map[1] = 100`:
```rust
fn main() {
    js! { Module.test = {}; }
    for _ in 0..100 {
        js! { return Module.test; }
    }
}
```

That leads to leaking JS objects.

See also [this comment](https://github.com/koute/stdweb/issues/92#issuecomment-370231597), fixing this would probably break IDs for same objects, since [they would be deleted](https://github.com/koute/stdweb/blob/85f7aa484f3be9808b992b9258bd85fa588e05b1/src/webcore/runtime.js#L332) from the WeakMap when reference count reaches zero, but there are still existing references in JS.

**Comment by Pauan** [comment]
I think we just shouldn't guarantee that the same id corresponds to the same JS object.

That does mean that the implementation of `PartialEq` on all `Reference`s will be slower though.

**Comment by kuviman** [comment]
@Pauan I thought it is actually a bug that objects are deleted from `ref_to_id_map`.

If they were not deleted, same ids would be guaranteed, and right now they are the same only because of the incorrect refcounting.

**Comment by Pauan** [comment]
@kuviman You're right, it should never delete from `ref_to_id_map`: it's a `WeakMap`, so it will automatically garbage collect the keys when they are no longer accessible in Rust or JavaScript.
