### ISSUE TITLE
linking failed

### ISSUE THREAD

**Issue by hon** [koute/stdweb#15]
Hi, bellow code can't compile:
```rust
#[macro_use]
extern crate stdweb;

fn main() {
    let message = "hello world";
    let result = js! {
        alert(@{message});
        return 2 + 2 * 2;
    };
    println!("2 + 2 * 2 = {:?}", result);
}
```

with windows 10 throws:
```bash
linking with `link.exe` failed: exit code: 1120
...
```

with macOS throws:
```bash
inking with `cc` failed: exit code: 1
...
```

what is the problem?
thanks.

**Comment by koute** [comment]
How are you building it? You can't just build it with `cargo build` as that will try to produce a native binary which won't work (it needs to be compiled into either asmjs or webasm). Try installing [cargo-web](https://github.com/koute/cargo-web) and building with `cargo web build`.
