### ISSUE TITLE
Expose WebSocket SocketReadyState?

### ISSUE THREAD

**Issue by DancingBard** [koute/stdweb#157]
https://github.com/koute/stdweb/blob/be80ba3b3f9a3fd8bc945a3ad190ded73d999c25/src/lib.rs#L228

Could `SocketReadyState` also be exposed here, so that one can use https://docs.rs/stdweb/0.4.1/stdweb/web/struct.WebSocket.html#method.ready_state?

Or is there a specific reason not to do that?

**Comment by koute** [comment]
Yes, the fact that it's not exposed was overlooked; I've fixed it on `master`. The fix will be available in `0.4.2` once I get to releasing it.

Thanks for the report!
