### ISSUE TITLE
Compilation on nightly fails

### ISSUE THREAD

**Issue by pitdicker** [koute/stdweb#175]
Because the `TryFrom` trait is stabilized https://github.com/rust-lang/rfcs/pull/1542

**Comment by pitdicker** [comment]
This is the relevant rust issue https://github.com/rust-lang/rust/pull/49305

**Comment by tirkarthi** [comment]
This seems to be reverted with the PR https://github.com/rust-lang/rust/pull/49518

**Comment by koute** [comment]
Looks like this is resolved. For now. So I'll be closing this issue.

I've already started to work on migrating to the `TryFrom`/`TryInto` traits from the stdlib, so hopefully we'll be better prepared next time it's added to the prelude.
