### ISSUE TITLE
atan2 bug with wasm32-unknown-unknown

### ISSUE THREAD

**Issue by Tacklebox** [koute/stdweb#182]
Despite atan working correctly, atan2 produces incorrect results.
I made a minimal setup that shows the bug at https://github.com/Tacklebox/atan2_bug
or if you just want some code that shows it 
````
    console!(log, f64::atan2(-42 as f64, 56 as f64));
    js!(console.log(Math.atan2(-42,56)));
````
It happens with f32 as well. The default emscripten target works as expected.

**Comment by CryZe** [comment]
It looks like this should be Math.atan2:
https://github.com/koute/cargo-web/blob/0404ffebfc51ebbc85aef5b88c5c4ed5d17db029/src/wasm_intrinsics.rs#L33

**Comment by koute** [comment]
Thanks for the report!

Should be fixed on the newest `master` of `cargo-web`; I'll release it on crates.io soon.

**Comment by koute** [comment]
I've released new `cargo-web` yesterday with a fix for this, so closing!
