### ISSUE TITLE
Request: create_document_fragment

### ISSUE THREAD

**Issue by togekk** [koute/stdweb#184]
Hi,
First thanks for the great library. But seems like "create_document_fragment" is not implemented at the moment. Can you add it into the code? Thanks!

**Comment by koute** [comment]
I'll take it into consideration. (:

However, if you'd like to have it added sooner I welcome you to try to do it yourself and create a PR.

**Comment by togekk** [comment]
Hi,
I forked your repo and added DocumentFragment and create_document_fragment. I've also added get_attribute in Node. The fork link is [here](https://github.com/togekk/stdweb).

**Comment by togekk** [comment]
Sorry I accidentially press the wrong button and close the issue. Now I reopened it

**Comment by togekk** [comment]
resolved #202
