### ISSUE TITLE
TypedArray memory leak

### ISSUE THREAD

**Issue by nosideeffects** [koute/stdweb#186]
I have been replacing some of my JavaScript matrix math type functions with variants that look like this:
```
#[js_export]
fn something(a: TypedArray<f64>) -> TypedArray<f64> {
    ...
}
```

Everything compiles and run fine, but it seems that the `TypedArray<f64>` that gets returned is never garbage collected. To work around this issue I've begun to simple return `Vec<f64>` as `Value` and copy the values back into a `Float64Array` on the JavaScript side:
```
let b = new Float64Array(something(a));
```

This is obviously inefficient and undesirable, but after a couple hours of investigate it is unclear if the issue lies in WASM land or is a v8 bug.

**Comment by koute** [comment]
Can you specify the versions of everything you're using? (Rust version, exact browser, OS, etc.)

Also, could you upload an example crate which reproduces this problem?

**Comment by qthree** [comment]
@koute https://github.com/qthree/stdweb_TypedArray_leak
Pressing button creates 1000 of Int32Array's with 1 million length each results in 4Gb leak. Pressing button once more will leak 4Gb more.

**Comment by koute** [comment]
Thanks a lot for the repro! Fixed on `master`.
