### ISSUE TITLE
How to register a function so that it runs repeatly?

### ISSUE THREAD

**Issue by astrojhgu** [koute/stdweb#189]
I tried to use the js! macro, it seems to work. However, according to the [js! doc](https://docs.rs/stdweb/0.4.2/stdweb/macro.js.html), any callbacks passed to js must be manually dropped to prevent memory leaking. Iif I follow this instruction, then an error will accur. If I do not drop the callback closure manually, everything seems to be ok. 

Maybe there is other more ``official'' method to register a function to run repeatly? If so what is it?

**Comment by Pauan** [comment]
Could you give more details about what you're trying to do?

**Comment by astrojhgu** [comment]
I'm just trying to display an animate on a canvas. More detailly, I'm going to implement the [game of life](https://en.wikipedia.org/wiki/Conway%27s_Game_of_Life)

**Comment by Pauan** [comment]
Okay, so you'll want to use `requestAnimationFrame`, like this:

```rust
fn game_loop<F>(callback: F) -> where F: FnMut(f64) + 'static {
    js! { @(no_return)
        var callback = @{callback};

        function loop(time) {
            requestAnimationFrame(loop);
            callback(time);
        }

        requestAnimationFrame(loop);
    }
}
```

And now you can use it like this:

```rust
game_loop(|time| {
    ...
});
```

Note: the above game loop never ends. I can write a version that ends, if you want, but it's more complicated.

Also, you can adapt it to use `setTimeout` instead, if you want, though I don't recommend doing that.

`requestAnimationFrame` is much more efficient than `setTimeout`, but it's locked to the monitor's refresh rate (which is usually 60 FPS).

However, you can compare the old `time` to the new `time` to "throttle" it so it fires slower than the monitor's refresh rate:

```rust
// 30 FPS
const FPS: f64 = (1000.0 / 30.0);

let mut old_time = None;

game_loop(move |time| {
    if old_time.map(|old_time| (time - old_time) >= FPS).unwrap_or(true) {
        old_time = Some(time);

        // Your code goes here
    }
});
```

Note: the above is completed untested, and may not be the best way to accomplish that.

**Comment by Pauan** [comment]
Also, here is the version which can be ended:

```rust
#[derive(Debug)]
pub struct GameLoop(Value);

impl GameLoop {
    pub fn new<F>(callback: F) -> Self where F: FnMut(f64) + 'static {
        GameLoop(js!(
            var callback = @{callback};

            function loop(time) {
                state.id = requestAnimationFrame(loop);
                callback(time);
            }

            var state = {
                callback: callback,
                id: requestAnimationFrame(loop)
            };

            return state;
        ))
    }
}

impl Drop for GameLoop {
    fn drop(&mut self) {
        js! { @(no_return)
            var state = @{&self.0};
            cancelAnimationFrame(state.id);
            state.callback.drop();
        }
    }
}
```

The above is a common pattern with stdweb when using callbacks.

Now you can use it like this:

```rust
// When `game_loop` is dropped it will stop the game loop
let game_loop = GameLoop::new(|time| {
    ...
});
```

**Comment by astrojhgu** [comment]
Thanks a lot!
I will try your solution.
