### ISSUE TITLE
Add pathname to Location

### ISSUE THREAD

**Issue by vitiral** [koute/stdweb#190]
Here is the full `window.location` object in javascript 
```
>> print(JSON.stringify(window.location, null, 4))
"{
    \"href\": \"http://krasimirtsonev.com/blog/article/A-modern-JavaScript-router-in-100-lines-history-api-pushState-hash-url\",
    \"origin\": \"http://krasimirtsonev.com\",
    \"protocol\": \"http:\",
    \"host\": \"krasimirtsonev.com\",
    \"hostname\": \"krasimirtsonev.com\",
    \"port\": \"\",
    \"pathname\": \"/blog/article/A-modern-JavaScript-router-in-100-lines-history-api-pushState-hash-url\",
    \"search\": \"\",
    \"hash\": \"\"
}"
```

Currently `Location` only includes `hash` and `href`. It seems to me like it should be zero-cost to include at _least_ pathname as well. Also, I think including _all_ of them would be at least useful.

Thoughts are welcome. I suppose an argument could be made that the user can parse the `href` directly if they want more information.

Thanks.

**Comment by koute** [comment]
Well... I'm not sure what you want to hear, but I don't see why not; it should be pretty trivial to add all of them. (:

**Comment by vitiral** [comment]
Yes is what I want to hear :smile: 

I can add them. Are we sure we want to keep the current type though?

```
pub fn href(&self) -> Result<String, TODO>
```

When you look at the code:
```
    pub fn href( &self ) -> Result< String, TODO > {
        Ok( js!(
            return @{self}.href;
        ).try_into().unwrap() )
    }
```
So it's expected to always succeed... and based on my playing around above everything is _always_ at least an empty string. Do you think these should change to just `pub fn _attribute_(&self) -> String`?

**Comment by vitiral** [comment]
there _is_ the possibility that [location itself is `null`](https://github.com/DenisKolodin/yew/issues/184#issuecomment-379402260), is that why these are fallible (although that is well covered by [`stdweb::web::Window::location`](https://docs.rs/stdweb/*/stdweb/web/struct.Window.html#method.location) being `Option`.

**Comment by koute** [comment]
[According to the specs those can throw an exception](https://html.spec.whatwg.org/#dom-location-href) (`SecurityError`), which is why they are `Result` (although nobody has yet gotten to replacing the placeholder `TODO` type with an actual error type).

And [according to the specs none of those can be non-string](https://html.spec.whatwg.org/#location), which is why they return `String` and not `Option< String >`. (Unless browsers *do* return a `null` for some of these fields sometimes?)

**Comment by vitiral** [comment]
Ah, the security issue explains why they are `Result`. Thanks!

**Comment by koute** [comment]
So if you're feeling like adding the rest of the fields you're very much welcome; just please while you're at it replace the `TODO` with a proper error type. (:
