### ISSUE TITLE
event::PopStateEvent erroniously states that it can be created by push_state or replace_state

### ISSUE THREAD

**Issue by vitiral** [koute/stdweb#191]
https://docs.rs/stdweb/*/stdweb/web/event/struct.PopStateEvent.html#method.state

>  If the history entry being activated was created by a call to `history.push_state()` or was affected by a call to `history.replace_state()`, the popstate event's state property contains a copy of the history entry's state object.

However, the `PopStateEvent` (`window.onpopstate`) will in fact never be triggered by `history.{push, replace}State()`, which is what [stdweb calls](https://docs.rs/stdweb/*/src/stdweb/webapi/history.rs.html#36).

https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onpopstate

> Note: calling history.pushState() or history.replaceState() won't trigger a popstate event. The popstate event is only triggered by performing a browser action, such as clicking on the back button (or calling history.back() in JavaScript), when navigating between two history entries for the same document.

**Comment by koute** [comment]
Both doc snippets you've pasted originally come from MDN, so are you saying they're wrong? (:

**Comment by vitiral** [comment]
it looks like we just need to include the _full_ documentation from here: https://developer.mozilla.org/en-US/docs/Web/API/PopStateEvent

the full docs state the second point.

Basically: yes, you get the state from `pushState` -- but only from a _previous_ `pushState` that you are now going back/forwards to.

**Comment by koute** [comment]
Sounds good to me!

**Comment by koute** [comment]
PR with the fix merged; thanks a lot!
