### ISSUE TITLE
Add support for SVG

### ISSUE THREAD

**Issue by vitiral** [koute/stdweb#196]
It would be great to add support for SVG so that we could render graphviz (among other things)

https://developer.mozilla.org/en-US/docs/Web/SVG

This looks to be an absolutely _massive_ undertaking. There are like [50 SVG Elements](https://developer.mozilla.org/en-US/docs/Web/SVG/Element) alone and well over [200 SVG Attributes](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute) and about [100 SVG Interfaces](https://developer.mozilla.org/en-US/docs/DOM/DOM_Reference#SVG_interfaces) (these numbers are just eyeballed).

I wonder -- is there some kind of shortcut we can take here for a (non-performant) MVP?

**Comment by vitiral** [comment]
related question: if I wanted to inject items in the DOM that are not yet supported (i.e. html elements obtained from a javascript library) is there a way to do that? Does this question even make sense? (I feel like it probably doesn't).

**Comment by Boscop** [comment]
Can you set `.innerHTML` to your string that contains the html?

**Comment by vitiral** [comment]
Hmm, some references:

- [w3 schools](https://www.w3schools.com/jsref/prop_html_innerhtml.asp): ` document.getElementById("demo").innerHTML = "Paragraph changed!";`
- [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML)

That might work, I'll have to experiment.

**Comment by vitiral** [comment]
I will be using graphviz, which creates a flat `<html>... <svg>...</svg></html>` string which I want to include directly into my `yew` application.

**Comment by Pauan** [comment]
Ah, I see, in that case using `innerHTML` is indeed correct.

I don't know much about Yew, but maybe setting the `innerHTML` attribute is enough:

```rust
html! {
    <div innerHTML=generate_graphviz_somehow()><div/>
}
```

You might also try something like this:

```rust
html! {
    <div>{generate_graphviz_somehow()}<div/>
}
```

**Comment by koute** [comment]
If there are some elements you need you can just create bindings yourself only for the stuff you actually need (since you *can* use `stdweb-derive` outside of `stdweb`). An alternative would be to maybe use the IDL parser + code generator on which @Diggsey worked to try to generate a usable set of basic bindings. (He used it to generate WebGL bindings.)

**Comment by vitiral** [comment]
@Pauan thanks, but none of those seem to work.

I tried to do it through javascript directly. @koute @Pauan maybe you can decipher what is happening?

https://github.com/vitiral/notes/blob/e9cc1a120b9e4f6920430ff1862f1ba729fc0ecd/rust/play_yew/src/main.rs#L88

```
        let js_node = js! {
            var div = document.createElement("div");
            div.innerHTML = @{SVG.to_string()};
            console.log(div);
            div
        };
        eprintln!("js_node: {:?}", js_node);

        let node = Node::try_from(js_node).expect("convert js_node");
        VNode::VRef(node)
```

The example compiles but doesn't render. The browser console states:

```
<div> (succesffuly printed)
counter_router.js:1971:168
js_node: Undefined
counter_router.js:557:7
Encountered a panic!
counter_router.js:2000:15
Panic error message: convert js_node: TypeMismatch { actual_type: "Undefined" }
counter_router.js:2001:21
Panic location: libcore/result.rs:945
```

**Comment by vitiral** [comment]
To be more clear:
- `html!{<div>{ SVG }</div>` just resulted in "raw" html text being displayed
- `html!{<div innerHTML=SVG,></div>}` did not show _anything_ (and no errors).

**Comment by vitiral** [comment]
agh, I'm an idiot. I forgot `return div;` in the `js!`.

The error is now:

```
Panic error message: not yet implemented: node can't be rendered now
```

**Comment by Pauan** [comment]
> (I'm WAY too used to rust 😄)

Here be dragons, lest you beware. The horrors of JavaScript are not for the faint of heart!

In all seriousness, there's many reasons I switched from being a 10+ year JavaScript developer to a Rust + Wasm developer.

**Comment by vitiral** [comment]
So I'm going to go ahead and close this since it _is_ supported via `innerHTML`. #199 will make it more ergonomic.

**Comment by vitiral** [comment]
Notice: You can now use `Node::from_html` for this usecase.

**Comment by Boscop** [comment]
Btw, there's another approach, using data URIs like
`<img src='data:image/svg+xml;charset=utf8,<svg ... > ... </svg>'>`,
but you have to percent-encode some chars, similar to this:
https://gitlab.com/ivanceras/svgeditor-simple/blob/master/src/main.rs#L36-39
But that one is encoding more chars than necessary (if you care about the SVG size / RAM usage):
https://codepen.io/tigt/post/optimizing-svgs-in-data-uris
https://docs.rs/url/1.4.1/src/url/percent_encoding.rs.html#98
