### ISSUE TITLE
WebGL teximage2D not working correctly with an ArrayBuffer

### ISSUE THREAD

**Issue by benkonz** [koute/stdweb#203]
I am trying to render out some generated texture data onto a texture with a WebGLRenderingContext. Here is my code:
```
// self.pixels is of type [u8; 144 * 160 * 4]
 let pixels = TypedArray::<u8>::from(&self.pixels[..]).buffer();

        self.context.tex_image2_d(
            gl::TEXTURE_2D,
            0,
            gl::RGBA as i32,
            160,
            144,
            0,
            gl::RGBA,
            gl::UNSIGNED_BYTE,
            Some(&pixels),
        );
```
When this code gets executed, I get  this error: `Argument 9 of WebGLRenderingContext.texImage2D does not implement interface ArrayBufferViewOrNull.` Pixels is a valid ArrayBuffer, so I am not sure what is going wrong.

**Comment by koute** [comment]
Can you post a minimal project which reproduces this?

cc @Diggsey

**Comment by benkonz** [comment]
I created a repo that demonstrates the error. Let me know if you have any questions.
https://github.com/benkonz/texture_issue

**Comment by koute** [comment]
So it looks like that function incorrectly takes `ArrayBuffer` while is should be taking `ArrayBufferView`, which is a helper interface [for typed array types and `DataView`](https://developer.mozilla.org/en-US/docs/Web/API/ArrayBufferView).

Here's the snippet from the [official IDL](https://www.khronos.org/registry/webgl/specs/latest/2.0/webgl2.idl):

```
void texImage2D(GLenum target, GLint level, GLint internalformat,
                  GLsizei width, GLsizei height, GLint border, GLenum format,
                  GLenum type, [AllowShared] ArrayBufferView? pixels);
```

And [here is the faulty line in gl_generator](https://github.com/brendanzab/gl-rs/blob/f2eb4d15801345eab88320acbb21766f01a7720c/webgl_generator/webgl_generators/stdweb_gen.rs#L135):

```
&TypeKind::ArrayBuffer | &TypeKind::ArrayBufferView => ProcessedArg::simple("&ArrayBuffer"),
```

**Comment by Diggsey** [comment]
I'm just working on a fix.

**Comment by Diggsey** [comment]
Here is a PR containing a fix:
https://github.com/brendanzab/gl-rs/pull/459

Here is a PR updating your example project:
https://github.com/benkonz/texture_issue/pull/1

**Comment by benkonz** [comment]
I am going to close this since https://github.com/brendanzab/gl-rs/pull/459 fixed this issue.
