### ISSUE TITLE
hasher parcel not working

### ISSUE THREAD

**Issue by simdax** [koute/stdweb#208]
Hello all.

Hasher is working correctly, but not the parcel one.
The site is served, but the hash does not appear. The web assembly can not be evaluated:

```
$(npm bin)/parcel index.html
Server running at http://localhost:1234 
⏳  Building loader-6688724b610665301fd2edbd72971722.js...
✨  Built in 3.44s.

10665301fd2edbd72971722.js:519:40: Cannot statically evaluate fs argument
  517 |         const path = require( "path" );
  518 |         const wasm_path = path.join( __dirname, "hasher.wasm" );
> 519 |         const buffer = fs.readFileSync( wasm_path );
      |                                         ^
  520 |         const mod = new WebAssembly.Module( buffer );
  521 | 
  522 |         return __initialize( mod, false );


```

**Comment by koute** [comment]
Thanks for the report!

I forgot to bump the dependencies of that example to the new version which is why it doesn't work. One of the patch versions in `parcel` 1.6.x series broke our plugin; I've fixed it so it should work with `parcel` 1.7.0 and `parcel-plugin-cargo-web` 0.2.0.

Unfortunately our Parcel plugin broke **yet again** in `parcel` 1.7.1... \*sigh\*

**Comment by simdax** [comment]
Thank you for your response.
I'm having trouble trying to lock the 1.7.0 version of cargo bundler. It appears that parcel-plugin-cargo-web installs automagically the 1.7.1 version. 
Is there a way to avoid this behaviour ?
Thank you!

**Comment by koute** [comment]
Untill I'll fix the plugin again you can install the older version of Parcel it manually:

```
npm install parcel-bundler@1.7.0
npm install parcel-plugin-cargo-web
```

**Comment by koute** [comment]
You need to get rid of `.cache`, `dist` and `node_modules`. You also possibly have to delete `package-lock.json`.

**Comment by simdax** [comment]
ok. I now have the good versions of the packages 
![deepinscreenshot_select-area_20180427083647](https://user-images.githubusercontent.com/2458806/39348145-2480a05e-49f6-11e8-9f94-d236f705f3a4.png)

I have the same warning as in the beginning of the post

![deepinscreenshot_select-area_20180427083946](https://user-images.githubusercontent.com/2458806/39348256-9a588300-49f6-11e8-9648-d787cd63e2d4.png)

rebuilding dont show the warning anymore but the result is the same, it still not works... :(

![deepinscreenshot_select-area_20180427083311](https://user-images.githubusercontent.com/2458806/39348126-1078b4c0-49f6-11e8-8dfc-ee6883f73467.png)

**Comment by koute** [comment]
The wrong `.js` runtime was generated, probably because you've build the `hasher` example manually (I really ought to add a check for this in `cargo-web`). Be sure to delete `.cache` and `dist`, and also delete the `target` directory in `examples`, and it should work then.
