### ISSUE TITLE
Feature request: expose webcore::executor::spawn_local

### ISSUE THREAD

**Issue by kzvi** [koute/stdweb#212]
Would it be possible to make that function public so that I can use it in my application? :)

**Comment by Pauan** [comment]
It already is exposed, as [`PromiseFuture::spawn_local`](https://github.com/koute/stdweb/blob/9e0d1add5c03ded403e55340fbe29b386cce76e6/src/webcore/promise_future.rs#L85)

**Comment by kzvi** [comment]
Oh, thanks, I didn't notice that.
