### ISSUE TITLE
How to work around recursion limit in js! macro

### ISSUE THREAD

**Issue by keeslinp** [koute/stdweb#219]
I've run into a problem where I'm defining a class in js-land using the js! macro that acts as an interface for a struct in rust-land. This means that a lot of data is passing back and forth in the class declaration. I've run into a recursion limit problem with _js_impl. What is the best way to work with that limitation? I saw that you raised the limit in #5 but I'm not sure how feasible it is to keep raising the limit.

here's the macro that's causing troubles:
```
    js! {
        window.customElements.define(@{name}, class extends HTMLElement {
            constructor() {
                super();
                @{clone!(component => move |element| component.borrow_mut().constructor(element))}(this);
            }
            connectedCallback() {
                @{clone!(component => move |element| component.borrow_mut().connected_callback(element))}(this);
            }
            static get observedAttributes() {
                return @{T::observed_attributes}();
            }
            attributeChangedCallback(...args) {
                @{
                    let clone = component.clone();
                    move |element, name, old_value, new_value| clone.borrow_mut().attribute_changed_callback(element, name, old_value, new_value);
                }(this, ...args);
            }
        });
    }
```

**Comment by Pauan** [comment]
I don't think the recursion limit has anything to do with #5.

You can raise the recursion limit in your crate by using this:

```rust
#![recursion_limit="1024"]
```

**Comment by keeslinp** [comment]
Oh, thanks :). I've never really understood macros, sorry for my ignorance!
I'll test that out when I get home

**Comment by koute** [comment]
Yeah; once procedural macros stabilize I plan to rewrite `js!` as a procedural macro which will alleviate the need to use `#![recursion_limit="..."]`, but as long as `js!` is a `macro_rules` macro it will hit the recursion limit on sufficiently big JS snippets.

**Comment by keeslinp** [comment]
That worked like a charm :). Thanks guys!
