### ISSUE TITLE
Response body of XmlHttpRequest

### ISSUE THREAD

**Issue by ryanisaacg** [koute/stdweb#227]
I'm looking at the XmlHttpRequest API and it doesn't seem like there's a way to [retrieve the body of the response](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/response) as a byte array. Would it be possible for this to be added? (I'm open to making a PR to add it, I just want to know if that would be in scope for stdweb before I do.)

**Comment by koute** [comment]
Sorry for the late reply.

Yes, of course it would be fine. In general *almost* everything that is in the official Web APIs specs is acceptable.

**Comment by ryanisaacg** [comment]
Closed by #240
