### ISSUE TITLE
Link error at runtime with #[js_export]

### ISSUE THREAD

**Issue by KelsonBall** [koute/stdweb#234]
I am building off of the [hasher example](https://github.com/koute/stdweb/tree/master/examples/hasher), trying to add another function that calls into a linear transformations crate

when I append 
```
#[js_export]
fn get_x( x: f64, y: f64 ) -> f64 {
    let t = AffineMatrix::new(Primitives::Translation(30.0, 30.0, 0.0));

    let position = t.apply_vec3( KVector3::new(x, y, 0.0) );

     position.x()
}
```

I get the following error when the module is loaded from javascript

```
Error loading Rust wasm module 'hasher': LinkError: Import #1 module="env" function="fma" error: function import requires a callable
    at __initialize (http://[::1]:8000/hasher.js:505:28)
    at fetch.then.then.then.mod (http://[::1]:8000/hasher.js:535:27)
```

I can't find any other examples of that error, specifically

` function="fma" error: function import requires a callable`

and have no idea what that means or where to start when trying to debug that

I'm using wasm32-unknown-unknown and rust nightly

(*two relevant notes: I am very new to rust, and I own the crate I am referencing)

**Comment by KelsonBall** [comment]
For anyone else having this issue, adding `"fma": console.log` to the `env` table in the generated javascript module ('hasher.js' in the targets folder for this example) gets my code to run. 

Since that's a manual change to a generated file that change gets lost sometimes during the build step

**Comment by koute** [comment]
Sorry for the late reply.

Thanks for the report! I've just fixed this; the fix is on the newest `master` of `cargo-web` and will be released sometimes this week.

**Comment by phiresky** [comment]
Can you say what you did exactly to fix this @koute ? Because I'm having a similar issue with log2f:

`LinkError: Import #1 module="env" function="log2f" error: function import requires a callable`

**Comment by phiresky** [comment]
Nevermind, looks like my issue was fixed by `rm .cache dist rus/target -rf`

**Comment by koute** [comment]
@phiresky The compiler automatically generates imports for a few built-in operations that have to be supplied externally (as WebAssembly doesn't support them natively); `cargo-web` automates that. It usually boils down to adding a new entry [here](https://github.com/koute/cargo-web/blob/master/src/wasm_intrinsics.rs).
