### ISSUE TITLE
How to use `put_image_data()` on canvas?

### ISSUE THREAD

**Issue by psiphi75** [koute/stdweb#235]
I'm stuck trying to get `put_image_data()` working with the canvas.  My problem is that I don't know how to initialise `ImageData`.

```Rust
  let img = ImageData {
    width: 5,
    height: 5,
    data: [0x0f as u8; 25 * 4],
  };
  ctx.put_image_data(img, 0.0, 0.0).unwrap();
```
This is not going to work because `struct ImageData(Reference)` defines a JavaScript reference.  

Sorry for the noob question.

**Comment by koute** [comment]
Sorry for the late reply.

You probably want to use [CanvasRenderingContext2d::create_image_data](https://docs.rs/stdweb/*/stdweb/web/struct.CanvasRenderingContext2d.html#method.create_image_data). I've improved the `ImageData` docs to reflect that.

If you have any futher questions feel free to ask. (:
