### ISSUE TITLE
js_try! with InvalidStateError

### ISSUE THREAD

**Issue by Joe-Jones** [koute/stdweb#236]
I am implementing result from the [IDBRequest](https://developer.mozilla.org/en-US/docs/Web/API/IDBRequest) interface. I am doing this in a trait as the [IDBOpenDBRequest](https://developer.mozilla.org/en-US/docs/Web/API/IDBOpenDBRequest) interface inherits IDBRequest properties (I'm unaware if there is better way of representing inheritance in the javascript APIs).

I want the method to look like 
```
fn result( &self ) -> Result<Value, InvalidStateError> {
        js_try!( return @{self.as_ref()}.result; ).unwrap()
    }
```
however this leads to a compilation error 
```
error[E0308]: mismatched types
   --> /home/ubuntu/stdweb/src/webcore/macros.rs:672:62
    |
672 |           if js!( return @{result.as_ref()}.success; ) == true {
    |  ______________________________________________________________^
673 | |             match js!( return @{result}.value; ).try_into() {
674 | |                 Ok(t) => Ok(Ok(t)),
675 | |                 Err(e) => Err(e),
676 | |             }
677 | |         } else {
    | |_________^ expected enum `webcore::value::ConversionError`, found enum `webcore::void::Void`
    | 
   ::: /home/ubuntu/stdweb/src/webapi/indexeddb.rs:40:9
    |
40  |           js_try!( return @{self.as_ref()}.result; ).unwrap()
    |           ------------------------------------------ in this macro invocation
    |
    = note: expected type `webcore::value::ConversionError`
               found type `webcore::void::Void`
```
I can see InvalidStateError being used with !js_try in rendering_context.rs lines 1202 and 1218. I'm unable to see how my usage differs, apart from the fact I'm using it in a trait ( I get the same error if I remove the method from the trait and add it to both IDBRequest and IDBOpenDBRequest though).

My working is in the branch [https://github.com/Joe-Jones/stdweb/tree/indexeddb](https://github.com/Joe-Jones/stdweb/tree/indexeddb) implemented in file [indexeddb.rs](https://github.com/Joe-Jones/stdweb/blob/indexeddb/src/webapi/indexeddb.rs).

Can anyone explain this error to me,

Thanks

**Comment by koute** [comment]
This happens because you're trying to return a `Value`, and a `TryInto` implementation for a `Value` -> `Value` conversion is infallible (so it returns `Void` as an error) while a `Value` -> `InvalidStateError` conversion is fallible (so it returns `ConversionError` as an error), so the two `if` branches end up having different types.

Fixed on `master`!
