### ISSUE TITLE
example panicked on wsl

### ISSUE THREAD

**Issue by gettf** [koute/stdweb#250]
on Windows Subsystem for Linux:

stdweb/examples/echo$ RUST_BACKTRACE=1 cargo web start --target=wasm32-unknown-unknown
warning: debug builds on the wasm32-unknown-unknown are currently totally broken
         forcing a release build
    Finished release [optimized] target(s) in 0.35s
    Garbage collecting "echo.wasm"...
    Processing "echo.wasm"...
thread 'main' panicked at 'unsupported custom section: '.debug_info'', src/wasm_context.rs:646:25
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:475
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:345
   7: cargo_web::wasm_context::Context::from_module
   8: cargo_web::wasm::process_wasm_file
   9: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &'a mut F>::call_mut
  10: cargo_web::cargo_shim::BuildConfig::build_internal
  11: cargo_web::cargo_shim::BuildConfig::build
  12: cargo_web::build::Project::build
  13: cargo_web::cmd_start::LastBuild::new
  14: cargo_web::main
  15: std::rt::lang_start::{{closure}}
  16: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  17: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:106
  18: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  19: main
  20: __libc_start_main
  21: _start

**Comment by koute** [comment]
Thanks for the report! Should be fixed with `cargo-web` `0.6.14`.
