### ISSUE TITLE
Bump syn & quote in stdweb-derive

### ISSUE THREAD

**Issue by lukaslueg** [koute/stdweb#257]
`syn` and `quote` was recently bumped to "0.14" and "0.6" for `stdweb-internal-macros`, which in turn updated `proc-macro2` to "0.4" from "0.2". Could you bump to those versions in `stdweb-derive` as well? There is currently a bug in `proc-macro2` that prevents compiling for wasm32 and fixing for `stdweb` would require that `proc-macro2` is on the most recent versions everywhere.

**Comment by koute** [comment]
Seems simple enough; done!
