### ISSUE TITLE
Issue when calling Rust from JS

### ISSUE THREAD

**Issue by alex-shapiro** [koute/stdweb#26]
Platform: OSX 10.12.6
Compiler: rustc 1.22.0-nightly (150b625a0 2017-10-08)

I have the following code:

```rust
extern crate stdweb;
use stdweb::Value;
use stdweb::unstable::TryFrom;

#[no_mangle]
pub extern fn print_value(v: Value) {
    println!("{:?}", &v);
    println!("{:?}", String::try_from(v));
}

fn main() {
    stdweb::initialize();
    stdweb::event_loop();
}
```

The code appears to compile just fine, but calling `_print_value` from JS leads to strange results:

```
_print_value(123)
> String("\u{0}\u{0}\u{0}\u{1}")
> Ok("\u{0}\u{0}\u{0}\u{1}")

_print_value("Hello")
> Maximum call stack size exceeded
```

The results I expected:

```
_print_value(123)
> Number(123)
> Err(...)

_print_value("Hello")
> String("Hello")
> Ok("Hello")
```

Have I been using `Value` incorrectly or is there a bug during translation from JS values to `Value`?

**Comment by koute** [comment]
Yes, this is currently not supported. Calling a Rust function from JS requires serialization and deserialization of passed parameters (which is not exactly trivial), so you can't just simply call a function like that directly. (It would be possible to get this to work, but it would require support from the compiler - support which we don't have yet.)

What you need to do is to export that function from your `main` manually and call that, e.g. something like this:

```
js! {
    global.print_value = @{print_value};
}
```

**Comment by alex-shapiro** [comment]
Ok, good to know. Is this something that's on the stdweb roadmap? I've been looking at https://github.com/RReverser/asmjs-experiments and it looks like he's figured out how to reverse-engineer embind to bring real interop between JS and Rust values (strings, arrays, and structs especially). Unfortunately it looks like development on the repo has stopped.

**Comment by koute** [comment]
Well, I'd definitely would want to support something like this in the future, although I'm not entirely sure if it's even possible to do it fully right now. When I'll have some time I might look into it more closely, but no promises.

**Comment by koute** [comment]
@alex-shapiro You might not be interested in this anymore, but newest `stdweb` will support a `#[js_macro]` attribute (it's already merged in on `master`) with which you can mark a function, and that functions will be then export and callable from JavaScript. This, I believe, will do exactly what you've requested. (It only works on `wasm32-unknown-unknown` target though.)

So, closing.

**Comment by RReverser** [comment]
> I've been looking at [RReverser/asmjs-experiments](https://github.com/RReverser/asmjs-experiments) and it looks like he's figured out how to reverse-engineer embind to bring real interop between JS and Rust values (strings, arrays, and structs especially). Unfortunately it looks like development on the repo has stopped.

Heh, that feeling when you accidentally come across a mention of your project few years ago after the fact. Too bad I haven't seen this back then.
