### ISSUE TITLE
How to get `TryFrom<Value>` for newtypes that wrap primitive types?

### ISSUE THREAD

**Issue by Boscop** [koute/stdweb#264]
```rust
#[derive(Serialize, Deserialize, Debug)]
struct Wrapper(u64);
```

> error: the trait `stdweb::webcore::try_from::TryFrom<stdweb::webcore::value::Value>` is not implemented for `Wrapper`

How to get `TryFrom<Value>` for newtypes that wrap primitive types?

**Comment by koute** [comment]
Implement it yourself? (: This isn't really a problem specific to `stdweb` - you'll have to do this for any other trait if you make a newtype wrapper.

**Comment by Pauan** [comment]
Yeah, it would be useful, but keep in mind that stdweb's `TryFrom` / `TryInto` will eventually be replaced with `std::convert::TryFrom` / `std::convert::TryInto`, so auto-deriving `TryFrom` / `TryInto` is a Rust stdlib issue, not a stdweb issue.

**Comment by koute** [comment]
Yep, it would be convenient to be able to do it in general, but alas, this is a problem which the whole Rust ecosystem has. If you need to do this a lot then you can always trivially make a macro yourself for your specific use case.
