### ISSUE TITLE
ConversionError { kind: Custom("invalid type: floating point 1535164942454, expected u64") }

### ISSUE THREAD

**Issue by Boscop** [koute/stdweb#265]
For geolocation I'm using:
```rust
#[derive(Debug, Deserialize)]
pub struct Position {
	pub coords: Coordinates,
	pub timestamp: DOMTimeStamp,
}
js_deserializable!(Position);
```
When I define [`DOMTimeStamp`](https://heycam.github.io/webidl/#DOMTimeStamp) as `u64`, it causes a panic when deserializing from `Value` (using `try_into`):
> ConversionError { kind: Custom("invalid type: floating point 1535164942454, expected u64") }

It works when I define it as `f64` but why doesn't it work with `u64`? It should convert without panic if there are no digits after the decimal point!

(I don't want to accidentally truncate the timestamp when converting from f64 to u64 with `as`.)

**Comment by koute** [comment]
Currently serde deserialization requires the types to strictly match. (The JS numbers are either serialized as `i32` or `f64`.)

Fixed on `master`. Thanks for the report!
