### ISSUE TITLE
Converting a vec into an array buffer

### ISSUE THREAD

**Issue by benkonz** [koute/stdweb#276]
How do I convert a `Vec<u8>` into an `ArrayBuffer`? I've tried this
```rust
// vector is of type Vec<u8>
let buffer: ArrayBuffer = self.vector.into();
```
but it doesn't look like ArrayBuffer can convert from a vector. Any help?

**Comment by koute** [comment]
You can create a `TypedArray` first and then grab the `ArrayBuffer`, e.g.: (types written out explicitly for clarity)

```rust
let slice: &[u8] = ...;
let array = TypedArray<u8> = slice.into();
let buffer: ArrayBuffer = array.buffer();
```

Of course if you feel like it then patches adding `impl From<&[u8]> for ArrayBuffer` and `impl From<Vec<u8>> for ArrayBuffer` are welcome. (:

**Comment by benkonz** [comment]
That works, thanks!
