### ISSUE TITLE
js_export with more than one argument results in a RuntimeError: index out of bounds

### ISSUE THREAD

**Issue by Theemuts** [koute/stdweb#286]
If I try to use the js_export attribute on a function which takes multiple arguments I get a RuntimeError when I try to call the exported function. I can only find examples which take a single argument among the test cases so I can imagine I'm just trying to do something which is not supported, but it's not clear to me from the documentation I can find.

**Comment by koute** [comment]
Thanks for the report!

Unfortunately I can't reproduce this. This should be supported, and the fact that there weren't really any tests for it is just an accidental omission. I added one here https://github.com/koute/stdweb/commit/1ae36164493f0939610acfdb8018364640848654 and it passes.

Are you using `stdweb` from `crates.io` or from current `master`?

Can you perhaps paste an example where you see this problem?

**Comment by Theemuts** [comment]
That's odd, this is one example that results in this error:

```
#[js_export]
fn join_strings(first: &str, second: &str) -> String {
    let mut result = String::new();
    result.push_str(first);
    result.push_str(second);

    result
``` 

If I take a single string and return another, it works as expected.

I'm using stdweb 0.4.9, rustc 1.30.0-nightly (887690686 2018-09-27), and trying to call the function in Firefox 62.0

**Comment by koute** [comment]
That also passes https://github.com/koute/stdweb/commit/7a392d38a634e395bcd32a5c8858545d646659e6 (:

Can you try using `stdweb` from `master`? Also, are you absolutely sure that the arguments you're passing are actually strings?

**Comment by Theemuts** [comment]
I'll give it a try and let you know the results. I'm sure the arguments are strings, and I haven't been able to successfully call any function with multiple arguments.

I just checked what happens in Chrome, but it just crashes immediately (Chrome 69)

**Comment by Theemuts** [comment]
No, I still have the same issues. I also tried using the most recent nightly, but nothing has changed. Functions with one argument work without any problems in both FF and Chrome, but if I try to use multiple arguments I get a RuntimeError in FF and Chrome crashes.

**Comment by Theemuts** [comment]
I've found the issue when I was unable to reproduce the issue in a new project... At some earlier point I had copied the compiled .js and .wasm file into my static directory, as a result I was always using a stale version. Everything worked as soon as I threw those two files away.

Thanks for your quick responses!
