### ISSUE TITLE
Shouldn't Window::set_timeout require F: 'static?

### ISSUE THREAD

**Issue by tomaka** [koute/stdweb#29]
I'm not very familiar with the way the library works, but to me the callback passed to `set_timeout` should be `'static`. Otherwise it could borrow a local variable and reference it after it's been destroyed.

**Comment by Herschel** [comment]
Yes, simple broken example:
```
extern crate stdweb;
use stdweb::web::{window, IWindowOrWorker};

fn main() {
    stdweb::initialize();
    {
        let x = Box::new(1);
        window().set_timeout(|| println!("{}", x), 3000);
    }
    stdweb::event_loop();
}
```

**Comment by koute** [comment]
Fixed; thanks for the report!
