### ISSUE TITLE
Bump crates.io for syn-update

### ISSUE THREAD

**Issue by lukaslueg** [koute/stdweb#291]
May it be possible to forward the version on crates.io to one where `syn-0.15` is a dependency of `stdweb-derive` and `stdweb-internal-macros` ? Those dependencies have already been updated from `0.14`, the currently available version on crates.io still depends on `0.14`, though. We could then bump `syn`, which needs bumping.

**Comment by koute** [comment]
Yes, sorry! I will release a new version on crates.io soon!

**Comment by silwol** [comment]
Adding interest from the Debian packaging team, these are the last two crates that prevent us from updating `syn` to 0.15.

**Comment by koute** [comment]
Apologies for the delay; `0.4.10` was just released!

Please let me know if there are any problems with it.
