### ISSUE TITLE
WASM-module fails to load in Firefox, loads fine in Chrome

### ISSUE THREAD

**Issue by lukaslueg** [koute/stdweb#292]
I have a wasm module that loads fine in Chrome, yet in Firefox I only get `Error loading Rust wasm module '...': <unavailable>`. I'm sorry for not providing more info - there isn't any. Some thoughts on how to debug this?

**Comment by koute** [comment]
That is interesting. How complex is your module? Can you post it? Can you post the sources?

What I would probably do is:
1) Make sure that the `.wasm` is correct with `wasm-validate`.
2) Convert it to `.wat`.
3) Successively remove code, recompile with `wat2wasm` and see if it still breaks. Do this until we get a minimal `.wasm` file which reproduces the issue.
4) Look at the minimized `.wasm` and think really hard. (:

**Comment by koute** [comment]
Also, perhaps it's using some newfangled WebAssembly feature which only Chrome supports, so it might be worthwhile to try Firefox nightly.

**Comment by lukaslueg** [comment]
`wasm-validate` has nothing to complain about. Nightly does not work as well. I'll resort to minimizing until it un-breaks.

Any way to get more output from Firefox other that "omfg it totally broke" ?

**Comment by Pauan** [comment]
@lukaslueg You can try putting this at the top of your `main` function:

```rust
::std::panic::set_hook(Box::new(|info| {
    console!(log, info.to_string());
}));
```

That might print more information.

**Comment by lukaslueg** [comment]
The whole code is [here](https://github.com/lukaslueg/macro_railroad_ext) now. It fails for Firefox on Linux (including Nightly) but works on Firefox for MacOS. I'm out of ideas :-)

**Comment by Pauan** [comment]
Oh! It's an extension! I see. The issue is probably with the differences between Chrome/Firefox extensions. Perhaps some sort of CSP restriction? Try putting this into your `manifest.json`:

```json
"content_security_policy": "script-src 'self' 'unsafe-eval'; object-src 'self';"
```

**Comment by Pauan** [comment]
You can also try setting an ID for the extension:

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/applications

It's not usually mandatory, but there are some situations where it is needed, so it might help.

**Comment by lukaslueg** [comment]
Yeah, I saw the CSP-setting (which would also allow me to access the WASM-module from the extension's options page), but I thought it was heavy-handed. Might give it a try, thanks.

**Comment by Pauan** [comment]
Yeah, it is heavy-handed, but probably necessary for now. [There is discussion happening](https://github.com/WebAssembly/content-security-policy/blob/master/proposals/CSP.md) about removing the need for `unsafe-eval` (and similar), but it's not standardized or implemented yet.

**Comment by lukaslueg** [comment]
It still fails with `ID` and `CSP` set. It works without on MacOS so I guess it's a Firefox bug. Will open an issue there, thanks :)

**Comment by lukaslueg** [comment]
This seems to be a general problem in Firefox which is now tracked [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1500710). You might be interested in the [workaround](https://bugzilla.mozilla.org/show_bug.cgi?id=1500710#c10), which applies to `cargo-web`.
