### ISSUE TITLE
Indirect fetch(<wasm-URL>) in js-shim

### ISSUE THREAD

**Issue by lukaslueg** [koute/stdweb#294]
When generating a wasm-module, the generated javacsript-shim uses `fetch ( 'name_of_module.wasm' )` to do the first stage of loading the wasm-module. This does not work in the context of a `WebExtension` (a browser addon-on) where we need to use `fetch ( chrome.runtime.getURL( "name_of_module.wasm" ) )`.

[Downstream](https://github.com/lukaslueg/macro_railroad_ext) I'm currently patching this. Maybe one could have a knob to turn?

**Comment by Pauan** [comment]
I also [do a similar regexp search-and-replace](https://github.com/Pauan/SaltyBetBot/blob/0d6840841f79c8db8badca10a159b964aece61c2/compile/src/main.rs#L26-L28) for my Chrome extension.

[There is support for a `--runtime library-es6` option](https://github.com/koute/cargo-web/issues/131), which you can use as a more robust way to set the URL (though it does require a bit more glue to make it work, and it also requires a bundler like Webpack or Parcel).

**Comment by lukaslueg** [comment]
I'm fine with patching the shim, so this can be closed if so desired.

**Comment by koute** [comment]
@Pauan Yeah, seeing as the only difference is a single line I don't have too much of a problem with it.

**Comment by Pauan** [comment]
[There is now support for a new `--runtime web-extension` flag.](https://github.com/koute/cargo-web/pull/151)

**Comment by lukaslueg** [comment]
I guess we can close here?! Closed :-)
