### ISSUE TITLE
Compile issues with stdweb 0.4.10

### ISSUE THREAD

**Issue by ryanisaacg** [koute/stdweb#296]
I'm getting the following compile issue:

```
   Compiling stdweb-derive v0.5.1
   Compiling stdweb v0.4.10
error[E0432]: unresolved import `stdweb_internal_macros`
   --> /Users/ryan/.cargo/registry/src/github.com-1ecc6299db9ec823/stdweb-0.4.10/src/lib.rs:141:9
    |
141 | pub use stdweb_internal_macros::js_export;
    |         ^^^^^^^^^^^^^^^^^^^^^^ Maybe a missing `extern crate stdweb_internal_macros;`?
error: aborting due to previous error
```

**Comment by koute** [comment]
Thanks for the report!

The `wasm32-unknown-unknown` target is currently only supported on nightly, although if you switch to at least Rust 1.30 it should work on stable too (I think; it's untested).

**Comment by ryanisaacg** [comment]
Looks like I was on an older version of nightly, updated and it works. Thanks for the help
