### ISSUE TITLE
Cannot compile the lib on Linux x86_64

### ISSUE THREAD

**Issue by BadLamb** [koute/stdweb#3]
This is the log: https://ghostbin.com/paste/kq2em

**Comment by koute** [comment]
Interesting!

What's your Rust/Cargo version? Where did you install it from?

Also, you're trying to compile it on root? I mean, I'm flattered by the trust you place in my library, but that's kinda dangerous isn't it? (;

**Comment by BadLamb** [comment]
I'm running inside a Docker container(https://hub.docker.com/r/janerik/rust-emscripten/), it's probably because my Rust is 6 months old :/. Thanks for the help

**Comment by koute** [comment]
That's what I thought.

I'm curious - could you check which exact version of Rust that container has? (`rustc --version`)

Well, yeah, unfortunately installing emscripten is a pain, although I might try to do something about it in the near future. (I have an [emscripten Travis build bot](https://github.com/koute/emscripten-build) set up; I just need to hook it up to [cargo-web](https://github.com/koute/cargo-web).)

**Comment by BadLamb** [comment]
`root@3d13feba5294:/asmjsvm/src# rustc --version
rustc 1.14.0-nightly (3caf63cc0 2016-10-24)
`

**Comment by koute** [comment]
I've added automatic Emscripten installation to `cargo-web` (Linux/x86-64 only for now), so hopefully now it won't be necessary to use antiquated containers just because they have Emscripten bundled.
