### ISSUE TITLE
New js macro strips whitespace before underscores, breaking usages of lodash

### ISSUE THREAD

**Issue by daboross** [koute/stdweb#316]
Hi! Found this issue upgrading from stdweb version 0.4.10 to 0.4.12.

Here's a minimal reproducing example:

```rust
#[macro_use]
extern crate stdweb;

use stdweb::unstable::TryInto;

fn main() {
    let sum: i32 = (js! {
        return _.sum([1, 2, 3]);
    })
    .try_into()
    .unwrap();
    println!("{}", sum);
}
```

When this is compiled using stdweb 0.4.11 or 0.4.12, the following JavaScript is generated:

```js
    env: {
        "__cargo_web_snippet_80036bccd04e4c0e0b63465745ea51e8ef93a554": function($0) {
        Module.STDWEB_PRIVATE.from_js($0, (function(){return_.sum([1,2,3]);})());
    },
```

As `return _` has become `return_`, it no longer works. This errors with `ReferenceError: return_ is not defined`.

The code compiles correctly using stdweb 0.4.10.

Let me know if there's anything I can do to help.

**Comment by daboross** [comment]
I think this line is to blame?

https://github.com/koute/stdweb/blob/c909666cca942f7a19d42b339664c57e830bf253/stdweb-internal-macros/src/js_stringify.rs#L22

in the function

https://github.com/koute/stdweb/blob/c909666cca942f7a19d42b339664c57e830bf253/stdweb-internal-macros/src/js_stringify.rs#L18-L31

`_` is not alphanumeric, but whitespace before/after it still matters in JS code.

**Comment by Pauan** [comment]
In addition to testing `_`, we should also test `$`, because `$` is a valid character in JS identifiers.

Technically most Unicode characters are valid in JS identifiers, so perhaps we should be even *more* lenient.

**Comment by daboross** [comment]
Perhaps checking for whitespace and a fixed set of operators might be best? This seems like something where there are a small set of characters which don't care about whitespace, not a fixed set of characters which do.


Something like this seems safe enough to me:

```rust
fn can_trim_whitespace_next_to(c: char) -> bool {
    c.is_whitespace() || "=+-*/%<>&^|~?:{}()[];.,".contains(c)
}
```

**Comment by koute** [comment]
@daboross I've implemented your suggestion on the newest `master`, and it should fix your case. If there aren't any objections (like, e.g. someone pointing out that it breaks another corner case) I'll release it within a few days.

**Comment by daboross** [comment]
I can confirm that this fixes it for my project after depending on git stdweb. Thanks for the quick work!

The only other case I could think of where this might need more handling is inline regex, but I would doubt the possibility of fully working inline regex anyways.

**Comment by daboross** [comment]
Works in stdweb 0.4.13.
