### ISSUE TITLE
Documentation link doesn't work at all.

### ISSUE THREAD

**Issue by Knifa** [koute/stdweb#320]
The main documentation link in the README (and on docs.rs directly) gives a "resource not found" error message.

**Comment by totorigolo** [comment]
More details on the error: https://docs.rs/crate/stdweb/0.4.13/builds

```
error[E0658]: use of unstable library feature 'pin' (see issue #49150)
 --> /home/cratesfyi/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-preview-0.3.0-alpha.11/src/future/mod.rs:4:5
  |
4 | use core::pin::Pin;
  |     ^^^^^^^^^^^^^^
  |
  = help: add #![feature(pin)] to the crate attributes to enable
```

However, the documentation is available for previous versions: https://docs.rs/stdweb/0.4.12/stdweb/

**Comment by koute** [comment]
Hmm... it looks like `docs.rs` was using too old version of the nightly compiler to compile a too recent version of the `futures-*` crates. I wonder if it's possible to force a rebuild on `docs.rs`?

**Comment by totorigolo** [comment]
I [asked](https://discordapp.com/channels/442252698964721669/459149231702278154/538154029071728643) on Discord on #rustdoc and _QuietMisdreavus_ started a new build, which was successful :tada:

Here it is: https://docs.rs/stdweb/0.4.13/stdweb/

**Comment by Knifa** [comment]
Works now. Thanks, friends!

**Comment by koute** [comment]
Thanks!
