### ISSUE TITLE
Canvas width/height properties documentation is incorrect.

### ISSUE THREAD

**Issue by yay** [koute/stdweb#322]
https://github.com/koute/stdweb/blob/5c4f1c5165d484545361e785539a28adffaf5dfb/src/webapi/html_elements/canvas.rs#L53

It says 

> Returns a positive integer reflecting the width HTML attribute of the <canvas> element interpreted in __CSS pixels__.

But is it?

The `canvas.width` and `canvas.height` attributes reflect the size of the canvas in actual pixels. The size of the image you'd get by right clicking a canvas element and selecting "Save Image As..." from the context menu. The size that is never tied to the `window.devicePixelRatio`. If `canvas.width` is 800, it will be 800 actual pixels wide on regular displays, on HDPI displays, as a detached node, etc.

While the CSS pixels are always tied to the device pixel ratio.
800 CSS pixels will mean 800 actual pixels on regular displays, 1600 actual pixels on retina displays, some other number on Google Pixel's display (pun intended)... you get the idea.

On the screenshot below we have a browser tab running on a rMPB's display, where we have the canvas with the width of 1600 actual pixels, but 800 CSS pixels (which translates into 1600 actual pixels, since `window.devicePixelRatio` is `2`). You can set `canvas.width` to any value, but the width in CSS pixels will remain 800.

<img width="1021" alt="screen shot 2019-02-10 at 16 04 42" src="https://user-images.githubusercontent.com/1799756/52534066-ad9d2700-2d4d-11e9-9bbd-9a5715c07a76.png">

**Comment by koute** [comment]
Thanks for pointing this out!

Our docs are usually directly copied from [MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/width), so if they're wrong then the MDN is wrong too!

I'll be happy to correct our docs if the MDN is also updated.

**Comment by yay** [comment]
MDN is not the spec. It's like the Wikipedia. Anyone can edit it. Do you want me to edit MDN?

**Comment by koute** [comment]
I know it's not the specs, and I'm very well aware that it might contain mistakes. (: I'm not implying that you're wrong in any way. It's just that it's simpler to more-or-less match what MDN says, since we link to it anyway. It would be confusing for the users if our docs will say one thing and the MDN says another.

If you edit the MDN I'll be happy to update our docs.

**Comment by yay** [comment]
Well, you know, I am actually kind of wrong and I apologize. The spec clearly says the `width` and `height` attributes set the size of the canvas's bitmap, and even makes a note:

> A canvas element can be sized arbitrarily by a style sheet, its bitmap is then subject to the object-fit CSS property.

http://w3c.github.io/html/semantics-scripting.html#the-canvas-element

But a canvas element with the default width and height of 300x150 pixels will actually occupy 600x300 physical pixels on retina screens (`window.devicePixelRatio` of 2) and the drawings will look blurry, unless you override the value of the attributes with a CSS style by setting the `canvas.style.width` to `150px` (which will set the CSS height to `75px` automatically, as evidenced by `getComputedStyle(canvas).height`, so no need to set `canvas.style.height` explicitly), which means that the canvas will now be 300x150 physical pixels in size and will look sharp, because the size of its bitmap now matches the physical pixels exactly. So the `canvas.width` and `canvas.height` attributes set both the size of the canvas's bitmap and, _when the canvas is attached to the DOM_, the size in CSS pixels as well. Sigh...
