### ISSUE TITLE
WebRTC support?

### ISSUE THREAD

**Issue by stusmall** [koute/stdweb#326]
I went looking for WebRTC support but couldn't find anything.  Is it currently supported?

**Comment by koute** [comment]
We currently do not have any actual bindings for WebRTC APIs. As a workaround you can always use them through the `js!` macro if you really need them.

**Comment by stusmall** [comment]
Outstanding.  Thanks for answer my question quickly.

**Comment by Pauan** [comment]
Also, keep in mind that we gladly accept PRs adding in more APIs.

It's not that hard, and we can help answer any questions/give advice.

**Comment by stusmall** [comment]
Outstanding.  I'll keep that in mind.  We've got an issue in our backlog related to it so y'all might see me again when it comes around.
