### ISSUE TITLE
Firefox hangs on js! call

### ISSUE THREAD

**Issue by jimmycuadra** [koute/stdweb#332]
I'm following [this tutorial](https://dev.to/deciduously/lets-build-a-rust-frontend-with-yew---part-3-ch3) on building a web app with Yew, and came to a point where running the code in Firefox hangs. After a few seconds Firefox displays a little bar that says "a web page is slowing down your browser" and provides the option to stop the script. Upon stopping it, the following error is emitted to the console:

```
Error: Script terminated by timeout at:
__cargo_web_snippet_77c7f20d9ad1903cb1faad4b79591e5576426760@http://localhost:8000/hunt-the-wumpus.js:582:17
_ZN15hunt_the_wumpus4util7js_rand17hb7b32a7f756b0960E@http://localhost:8000/hunt-the-wumpus.wasm:wasm-function[398]:0x417ae
_ZN15hunt_the_wumpus4game4Game14configure_cave17hdd6a0e1c2a7d0206E@http://localhost:8000/hunt-the-wumpus.wasm:wasm-function[240]:0x296d5
_ZN63_$LT$hunt_the_wumpus..Model$u20$as$u20$yew..html..Component$GT$6update17h31b42414e0699416E@http://localhost:8000/hunt-the-wumpus.wasm:wasm-function[344]:0x37cfe
_ZN85_$LT$yew..html..ComponentEnvelope$LT$COMP$GT$$u20$as$u20$yew..scheduler..Runnable$GT$3run17h0453ba83ec062212E@http://localhost:8000/hunt-the-wumpus.wasm:wasm-function[159]:0x116ce
_ZN3yew9scheduler9Scheduler15put_and_try_run17h032f100b34ca56ffE@http://localhost:8000/hunt-the-wumpus.wasm:wasm-function[407]:0x41ff9
_ZN229_$LT$stdweb..webcore..newtype..Newtype$LT$$LP$stdweb..webcore..serialization..FunctionTag$C$$u20$$LP$A12$C$$RP$$RP$$C$stdweb..webcore..mutfn..Mut$LT$F$GT$$GT$$u20$as$u20$stdweb..webcore..serialization..FuncallAdapter$LT$F$GT$$GT$15funcall_adapter17hd8e30ed85274ca16E@http://localhost:8000/hunt-the-wumpus.wasm:wasm-function[359]:0x3b672
Module.STDWEB_PRIVATE.dyncall@http://localhost:8000/hunt-the-wumpus.js:474:12
output@http://localhost:8000/hunt-the-wumpus.js:174:17
```

The offending line in `hunt-the-wumpus.js` is:

``` javascript
Module.STDWEB_PRIVATE.from_js($0, (function(){return Math.random();})());
```

This all comes from the following Rust code:

``` rust
use stdweb::unstable::TryInto;

pub fn js_rand(bottom: u8, top: u8) -> u8 {
    let rand = js! {
        return Math.random();
    };
    let base: f64 = rand.try_into().unwrap();

    (base * top as f64).floor() as u8 * bottom
}
```

I tried removing the `js!` call and just hardcoded a Rust f64 value to see what would happen. Running the program still hangs the browser tab, and upon stopping it, the following error is emitted to the console:

```
Error: Script terminated by timeout at:
_ZN15hunt_the_wumpus4game4Game14configure_cave17hdd6a0e1c2a7d0206E@http://localhost:8000/hunt-the-wumpus.wasm:wasm-function[196]:0x1ab35
_ZN63_$LT$hunt_the_wumpus..Model$u20$as$u20$yew..html..Component$GT$6update17h31b42414e0699416E@http://localhost:8000/hunt-the-wumpus.wasm:wasm-function[338]:0x37f28
_ZN85_$LT$yew..html..ComponentEnvelope$LT$COMP$GT$$u20$as$u20$yew..scheduler..Runnable$GT$3run17h0453ba83ec062212E@http://localhost:8000/hunt-the-wumpus.wasm:wasm-function[167]:0x13029
_ZN3yew9scheduler9Scheduler15put_and_try_run17h032f100b34ca56ffE@http://localhost:8000/hunt-the-wumpus.wasm:wasm-function[407]:0x41cc8
_ZN229_$LT$stdweb..webcore..newtype..Newtype$LT$$LP$stdweb..webcore..serialization..FunctionTag$C$$u20$$LP$A12$C$$RP$$RP$$C$stdweb..webcore..mutfn..Mut$LT$F$GT$$GT$$u20$as$u20$stdweb..webcore..serialization..FuncallAdapter$LT$F$GT$$GT$15funcall_adapter17hd8e30ed85274ca16E@http://localhost:8000/hunt-the-wumpus.wasm:wasm-function[353]:0x3b89c
Module.STDWEB_PRIVATE.dyncall@http://localhost:8000/hunt-the-wumpus.js:474:12
output@http://localhost:8000/hunt-the-wumpus.js:174:17
```

Which corresponds to a loop in the wasm file:

``` wat
loop $label8
  get_local $var1
  i32.const 0
  i32.store8 offset=16
  get_local $var1
  i32.const 16
  i32.add
  get_local $var2
  i32.const 6
  call $_ZN49_$LT$i8$u20$as$u20$core..slice..SliceContains$GT$14slice_contains17h7841e984ad0bfbccE
  br_if $label8
end $label8
```

I'm not sure how helpful that is out of context. The reference to core::slice::SliceContains makes me think it might be related one of the places `contains` is called on a slice elsewhere in the program. I don't know if that has any connection to the previous error related to calling `Math.random`. Perhaps these are two unrelated errors and removing the first one simply allows the program to proceed far enough to hit the second one.

I'm compiling the program on macOS using `cargo web start --release`, using cargo-web 0.6.23 and stdweb 0.4.15.

Any idea if I've encountered a bug in stdweb or if I've done something wrong on my end? I'm happy to provide more information if I haven't offered enough context to see what the problem might be.

**Comment by koute** [comment]
Hmmm... from what you've wrote it looks like it's working correctly; it just hogs the main thread a little too much.

If you do not stop the script then does it eventually finish?

Can you also try in Chrome and Safari?

**Comment by jimmycuadra** [comment]
I clicked "wait" a few times instead of stopping the script and each time it would hang until the message popped up again.

Chrome and Safari both hang indefinitely without any intervention like what Firefox does.

**Comment by Pauan** [comment]
I noticed your `js_rand` function doesn't follow the tutorial:

```rust
pub fn js_rand(bottom: u8, top: u8) -> u8 {
  let rand = js! { return Math.random(); };
  let base: f64 = rand.try_into().unwrap();
  (base * top as f64).floor() as u8 + bottom
}
```

Note that the tutorial uses `+ bottom`, not `* bottom`. That's very important! Since your code is always multiplying by `1`, that means the result isn't right.

**Comment by jimmycuadra** [comment]
Wow, that was it! Thank you @Pauan! I guess I need to increase my font size so I can distinguish `*` and `+` better. :}

Is there any takeaway here for stdweb? Like, any way that it could have produced a failure that would have been easier to debug? If there's nothing to be done I can just close the issue.

**Comment by Pauan** [comment]
> Is there any takeaway here for stdweb? Like, any way that it could have produced a failure that would have been easier to debug? If there's nothing to be done I can just close the issue.

I don't think so. Infinite loops are hard to debug in any language.

Eventually wasm will have good integration with the browser's debugger, and that will help, but I don't think that requires stdweb to do anything.
