### ISSUE TITLE
0.4.16 docs.rs build failure

### ISSUE THREAD

**Issue by dcecile** [koute/stdweb#336]
The docs.rs build is failing for [0.4.16](https://docs.rs/crate/stdweb/0.4.16):

![image](https://user-images.githubusercontent.com/311866/57005810-f1fbce80-6ba8-11e9-81f7-5b6f3e63ac86.png)

Build log: https://docs.rs/crate/stdweb/0.4.16/builds/155017

**Comment by dcecile** [comment]
The docs.rs badge link from the README ([line 10](https://github.com/koute/stdweb/blame/master/README.md#L10)) is also broken, not sure if it's related? https://docs.rs/stdweb/*/stdweb/

**Comment by koute** [comment]
Thanks for letting me know!

This should be fixed on `master`. I'll release a new version tomorrow which should hopefully fix the docs.rs link.

**Comment by dcecile** [comment]
The build and the link are both fixed now, thanks! 👏
