### ISSUE TITLE
Example for using FileReader onload callback

### ISSUE THREAD

**Issue by Adjective-Object** [koute/stdweb#338]
Sorry if this is obvious and I'm just missing something. New to rust here.

I'm trying to figure out how to use FileReader in stdweb.
The API inherited from JS is designed to be used like:

```
reader.addEventListener('loadend', () => {
   doAThing(reader.result)
});
```

But in rust I can't pull the reader's result out in the callback.
- if I move the reader into the callback, I can no longer bind the event listener
- if I don't move the reader into the callback, it won't compile because the reader won't be on the stack anymore by the time the callback is called.

What's the solve here? Is cloning the reader object safe? (e.g. will it still refer to the same reader as far as the browser is concerned)?

**Comment by koute** [comment]
> What's the solve here? Is cloning the reader object safe? (e.g. will it still refer to the same reader as far as the browser is concerned)?

Yes, that's exactly what you're supposed to do. The vast majority of the types in `stdweb` have reference semantics, that is - you can `.clone()` them and they will still reference the same object.

> Sorry if this is obvious and I'm just missing something. New to rust here.

It's no problem. Feel free to ask away if you have any problems and I'll be happy to help. (:

**Comment by Adjective-Object** [comment]
Thanks for the help!
