### ISSUE TITLE
Events aren't properly reexported

### ISSUE THREAD

**Issue by CryZe** [koute/stdweb#35]
It doesn't seem like the types necessary for actually using the event handlers are reexported.
https://docs.rs/stdweb/0.1.3/stdweb/web/trait.IEventTarget.html#method.add_event_listener

Both EventListenerHandle and ConcreteEvent are private types that leaked out (that shouldn't have been private in the first place)

**Comment by koute** [comment]
Fixed on master; thanks for the report!
