### ISSUE TITLE
Add window.confirm?

### ISSUE THREAD

**Issue by rickycodes** [koute/stdweb#352]
Took a spin through the repo and noticed there's no method exposed for `window.confirm` https://developer.mozilla.org/en-US/docs/Web/API/Window/confirm... Is this something I could add? Let me know if you have any suggestions for how you'd like to see this implemented... Assuming I'd just add it to `src/webapi/global.rs`. @koute I've already abstracted it a bit on my website, but it's slightly different than spec so I am curious to hear what your thoughts are...

This is what I have:
```rust
pub fn confirm(msg: String, a: fn(), b: fn()) {
    js! {
      var call_drop = fn => fn() && fn.drop();
      window.confirm(@{msg}) ? call_drop(@{a}) : call_drop(@{b});
    }
}
```
and then calling it:
```rust
confirm("U sure?".to_string(), del, reset)
```

I guess `confirm` should simply return a bool if we want to be closer to spec?

**Comment by koute** [comment]
Sorry for the delay.

Sure. This seems pretty straightforward to add. Something like this would be okay:

```rust
impl Window {
    fn confirm( &self, message: &str ) -> bool { ... }
}
```

**Comment by rickycodes** [comment]
@koute no worries re: reply

normally I'd just PR, but I didn't want to drive-by this time

I'll open a PR shortly

**Comment by rickycodes** [comment]
going to go ahead and close this now that it's been merged! thanks for letting me contribute, cc @koute
