### ISSUE TITLE
Local count too large, wasm loading error

### ISSUE THREAD

**Issue by madmaxio** [koute/stdweb#353]
After recent updates on windows debug build (mac os is ok) having this error on app loading:

`Error loading Rust wasm module 'my_app': CompileError: WebAssembly.compile(): Compiling function #27911 failed: local count too large @+7935353
localhost/:1 Uncaught (in promise) CompileError: WebAssembly.compile(): Compiling function #27911 failed: local count too large @+7935353`

Release build works fine.

**Comment by koute** [comment]
Sounds like a codegen bug with `rustc` and/or LLVM. Can you perhaps upload a minimal example which reproduces the issue?

**Comment by madmaxio** [comment]
Seems it doesn't appear now.
