### ISSUE TITLE
Allow converting Object into HashMap with key-type which implements FromStr?

### ISSUE THREAD

**Issue by daboross** [koute/stdweb#359]
Right now, there are several ways to convert objects to rust `HashMap`s, but none are exactly ideal for custom key types (which implement `FromStr`).

There's an impl `TryFrom<Value> for HashMap<String, V>`, but this forces the key type to be a string.

There's using `stdweb::serde::Serde` to wrap the `HashMap<MyKey, V>`, but this doesn't allow the value to be a reference-type.

Then there's the option of using retrieving a `HashMap<String, V>`, using `into_iter()`, converting keys, and building a second `HashMap` of the correct types. This works, but is inefficient in that it requires allocating two full `HashMap`s to do the conversion.

Would it be reasonable to have a method on `Object` for converting to `HashMap<K, V>`, using either `FromStr` or a custom conversion function for the key conversion?

The code implementing the impl `TryFrom<Object> for HashMap<String, V>` uses an internal function `deserialize_object` which I think could be used to implement this, but I'm not sure.

**Comment by koute** [comment]
> Would it be reasonable to have a method on `Object` for converting to `HashMap<K, V>`, using either `FromStr` or a custom conversion function for the key conversion?

Hmm... sure!

**Comment by daboross** [comment]
Awesome! I'll work on implementing that.

One thing I'm wondering about is the right error type for this. If it uses `FromStr` implementations, then those will have their error types - and there could still be errors from the `TryFrom<Value>` impls. I don't think there's a useful conversion from something like `std::num::ParseIntError` into `ConversionError` at the moment, though.

I guess I'll just make a PR for a `to_map_parsing_keys` function with an argument for `FnMut(&str) -> Result<K, ConversionError>` and let the user figure that out? I think `ConversionError` is fairly constructable by doing something like `stdweb::serde::ConversionError::custom(msg).into()`.
