### ISSUE TITLE
`wasm32-unknown-unknown` support (ie: WebAssembly without Emscripten)

### ISSUE THREAD

**Issue by neon64** [koute/stdweb#36]
As you've probably heard, support for the native LLVM wasm target in rustc has landed. I understand that this doesn't do much yet, however I'd be interested to see if its possible to get a minimal version of stdweb working, without the emscripten API/runtime.

All the examples I can find (eg: https://www.hellorust.com/demos/) seem to be about using Rust code as a library (with a C FFI), and then driving it from Javascript. To go the other way around, it seems like you can import certain JS functions and call them from WebAssembly code (https://gist.github.com/cure53/f4581cee76d2445d8bd91f03d4fa7d3b). I doubt that alone would be enough to implement a `js!` macro like we have for emscripten, though.

Anyway, I guess I wanted to open this issue not because I expect anyone to immediately implement everything, but rather to start some discussion around the feature (as I believe the future of wasm probably doesn't involve emscripten), and to ask if you had any tips for how I could try to implement it myself.

**Comment by koute** [comment]
Yes, I'm planning to play with this once I'll have some more free time (Probably this week.) and *maybe* get something going.

It should be technically possible to whip up an initial working prototype provided you'll export `eval` (and possibly a few other bits and bobs needed for memory management) from the JS into wasm, and then use that to execute the stuff passed into `js!`. Shouldn't be *too* hard, although it will probably require some elbow grease.

**Comment by kije** [comment]
+1

**Comment by neon64** [comment]
According to [the emscripten docs](https://kripken.github.io/emscripten-site/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html#interacting-with-code-call-javascript-from-native), `emscripten_asm_const` doesn't actually call `eval`, but rather `emcc` searches the LLVM bitcode for calls that function, and performs a little bit of magic.
As far as I understand it, `emcc` (at compile time) takes the string of JS code provided as the argument to `emscripten_asm_const`, inserts it into an array of 'user functions' in the JS wrapper script. Then, at runtime, the WASM code just calls into the wrapper script, which indexes that array to get the matching JS code, and then executes it. That way there's no `eval`ing at runtime, which should bring better performance.

Recreating a `js!` macro without emscripten, that has the same performance, would thus require similar magic inside the Rust compiler (or as a plugin). Perhaps then it is easier to write a seperate JS wrapper function for each each possible js operation (eg: `add_event_listener`,`query_selector_all`, etc...), and then expose them to WASM like so:

```js
var importObject = {
  imports: {
      imported_func: function(arg) {
        console.log(arg);
     }
   }
};

WebAssembly.instantiate(bytes, importObject)
```

Of course, once WASM gains native GC/DOM support we'll be able to rethink this entirely.

**Comment by koute** [comment]
@neon64 Yep. After doing some research I've decided to go all the way and immediately do what Emscripten does instead of going the `eval` route. I'm happy to report that it shouldn't require any support from the compiler to implement; in fact, I already have it, like, 70% done, so expect full support for wasm in both `stdweb` and `cargo-web` Very Soon™. (:

**Comment by chpio** [comment]
How does it work? I guess by parsing the files and generating a js file containing all the js functions and a rs file with all the js functions replaced by a call to the js file? Id would really nice if you could publish that tool so we could use it for our custom `js!` code.

**Comment by koute** [comment]
@chpio Well, basically:

1) I load the wasm bytecode which the compiler generates,
2) I search for any use of imported `js!` shim functions (which take a pointer to the JS code as an argument, basically something like Emscripten's `emscripten_asm_const_int`, just non-variadic and with a different order of parameters to make it easier),
3) I replace those with a bunch of autogenerated imports, each import corresponding to a JS snippet in the code (basically every call into a JS gets its own unique function which wasm bytecode imports),
4) I emit those JS snippets as imports in a `.js` file.

It will be part of my [cargo-web](https://github.com/koute/cargo-web) tool.

**Comment by koute** [comment]
I'm happy to announce `wasm32-unknown-unknown` is now supported!

**Comment by neon64** [comment]
Thanks @koute! I tried it today and its 99% awesome, but I've got one slight issue.

`stdweb::event_loop();` used to never return, and so I could allocate objects in the main() function that would stick around for the entire lifecycle of the program. However on the `wasm32-unknown-unknown` target it returns immediately and all my objects get deallocated! Is this change in behaviour intended?

**Comment by koute** [comment]
@neon64 Yes, that is intended since `wasm32-unknown-unknown` doesn't actually need it. I could *maybe* emulate it somehow, but I'm not sure if it's worth it. For now if you need something to stay alive for the lifetime of your program you could simply just leak it, for example [with this](https://crates.io/crates/leak).

**Comment by neon64** [comment]
That sound's perfectly reasonable. I'm sorry I didn't check the updated [docs](https://docs.rs/stdweb/*/stdweb/fn.event_loop.html) - I see you do in fact have it all documented.

**Comment by koute** [comment]
No problem; don't worry about it. (:
