### ISSUE TITLE
Best way to pass a Rust object opaquely to JS?

### ISSUE THREAD

**Issue by ColonelThirtyTwo** [koute/stdweb#374]
I need to pass some complicated types that don't implement Serializable through Promises. The JS code doesn't need to mess with the object at all, so the object can be mostly opauqe

Some example code (pretend `JsBox` is some struct that does what I want):

	struct SomeComplicatedStruct {}
	
	let value = Arc::new(SomeComplicatedStruct{});
	
	let boxed_value = JsBox::new(Arc::clone(&value));
	let then_cb = |boxed: stdweb::Value| {
		let value_ref: SomeComplicatedStruct = JsBox::from_value(boxed).unwrap();
		value_ref.do_something();
	}
	
	let promise = js!{
		Promise.fulfill(@{boxed_value})
			.then(function(v) {
				let cb = ${then_cb};
				cb(v);
				cb.drop();
			}, function(err) {})
	};
	
	// ...

I was wondering if there was a good way to do this that already exists? If not, I can possibly implement `JsBox` myself by putting the object in a `Box` and serializing the pointer as an integer, converting it back in `from_value`.

**Comment by Pauan** [comment]
Since you don't need to access the Rust value from JS, this is actually really easy:

```rust
struct SomeComplicatedStruct {}

let value = Arc::new(SomeComplicatedStruct{});

let boxed_value = Arc::into_raw(Arc::clone(&value)) as u32;

let then_cb = |boxed: u32| {
	let value_ref = unsafe { Arc::from_raw(boxed as *const SomeComplicatedStruct) };
	value_ref.do_something();
}

let promise = js!{
	Promise.fulfill(@{boxed_value})
		.then(${Once(then_cb)}, function(err) {})
};
```

**Comment by ColonelThirtyTwo** [comment]
@Pauan Yeah, that was the approach I was looking at in my last paragraph. Guess I'll do that.
