### ISSUE TITLE
serde_json usage within stdweb?

### ISSUE THREAD

**Issue by bbyler** [koute/stdweb#38]
(Creating a separate issue here; the PR already has enough going on)

Background: I noticed the src/ecosystem mods there, with serde and serde_json already present. Great idea btw! 

I'm particularly curious about ecosystem/serde_json. It doesn't look like it's really used anywhere, but it has a critical ```TryFrom``` implementation. Question 0: as it stands, does this work? (Looks good to me...)

If it does, then here's the situation: say I have a block of serde JSON, e.g.

```rust
let s =  r#"{"greeting_string": "hello"}"#;
let json_object: Value = serde_json::from_str(s)?; <-- serde_json Value, not stdweb Value...
// pretty cool that this works, without strong typing
println!(json_object["greeting_string"]); // hello
```

Nothing new here. 

Say we want to do something with it in stdweb, e.g.

```rust
use serde_json::value::Value as JsonValue;
use webcore::value::Value;

fn say_hello_to_world(json_value: &JsonValue) {
    // assuming a json_value object has a key and value for "greeting_string" and so on
    js!( @(no_return)
        console.log(@{json_value["greeting_string"]} + " world!");
    );
}
```

This example will break, since a serde JsonValue can't be marshaled into a JS object *without that ecosystem tie-in* (or a similar tie-in or implementation). How can that be done?

I've tried some stuff on my own and it blew up in my face...

As for now, this could be a documentation question, unless there is more involved in integrating with stdweb. Either way, I can see about documenting it in the README

Thanks!

**Comment by DenisKolodin** [comment]
@bbyler JS has another representation than Rust. Use `TryInto`:

```rust
let s =  r#"{"greeting_string": "hello"}"#;
let json_object: serde_json::Value = serde_json::from_str(s).unwrap();

let json_value: stdweb::Value = json_object.try_into().unwrap();

js!( @(no_return)
    var obj = @{json_value};
    console.log(obj["greeting_string"] + " world from raw JS!");
);
```

**Comment by bbyler** [comment]
I was very much overcomplicating this. Thanks @DenisKolodin for the well-written response! Confirmed that this works for arrays and objects (hashes). This is great!
