### ISSUE TITLE
Handling promises

### ISSUE THREAD

**Issue by thiagopnts** [koute/stdweb#44]
Is passing rust closures the only way to handle async stuff?
e.g. is it possible to do something like this:
```
    let promise = js!{
        return fetch(@{url})
            .then(response => response.text());
    };
    // unwrap promise somehow?
```

**Comment by CryZe** [comment]
I‘m working on a tokio / hyper for stdweb based on futures + http crates. That nicely integrates the web‘s async ecosystem with rust‘s with very little complexity or additional runtime. I‘ll try to release it over the next couple of weeks.

**Comment by koute** [comment]
@thiagopnts Currently yes, the only way to handle async stuff is through closures. Until `stdweb` itself supports more that that (It will! Although I can't say when exactly.) you might want to check out @CryZe 's [stdweb-io](https://github.com/CryZe/stdweb-io) (With a caveat that as far as I can see `stdweb-io` still has `stdweb 0.1` in its `Cargo.toml`, so you'd have to bump that up to `0.2`.)

**Comment by thiagopnts** [comment]
ok, thanks @CryZe and @koute!

**Comment by Pauan** [comment]
@thiagopnts We've recently added in [excellent support](https://github.com/koute/stdweb/pull/103) for JavaScript Promises and Rust Futures (and the ability to convert from JavaScript Promises to Rust Futures).

It's not released yet, but it should be in the next version of stdweb (0.4.0).

**Comment by koute** [comment]
@Pauan I'm going to release `0.4.0` very soon (probably tomorrow or the day after, I still need to apply some finishing touches, update the README, etc.), however I'm not going to include Promises in it just yet. That said, we can probably have them in `0.4.1`. (I do plan to release new versions more frequently in the future.)

**Comment by Pauan** [comment]
@koute What's blocking you from including Promises in `0.4.0`? As far as I know, I fixed all the blocking issues.

**Comment by thiagopnts** [comment]
its looking nice, thanks @Pauan!
