### ISSUE TITLE
Extend `js!` macro to support more arguments through interpolation

### ISSUE THREAD

**Issue by koute** [koute/stdweb#5]
Currently the `js!` macro only supports a few arguments, e.g.:

```rust
js!( return @{var1} + @{var2} + @{var3}; );
```

It'd be nice to extend it to support more, at least 10.

* Extend `js!` macro to support more arguments.
* Write a test for it in `serialization.rs`.

**Comment by gliheng** [comment]
Hi, what's the status of this issue? as I came into this one today. I've seen those crazy macros. No idea how to fix this. :(

**Comment by gliheng** [comment]
Thank you, that'll be really helpful!

**Comment by koute** [comment]
@gliheng Fixed on `master`!
