### ISSUE TITLE
Provide an ergonomic way to move (rather than copy) data into wasm

### ISSUE THREAD

**Issue by spease** [koute/stdweb#53]
Eg implementing From<Vec> for TypeArray. I believe this should be as simple as taking ownership of a Vec, calling into_typed_array_no_copy on as_slice, and then calling std::mem::forget on the vec before returning the TypeArray. Does this sound right?

**Comment by koute** [comment]
Hmm... unless I'm missing something I don't think that would work well. Not only it would result in a permanent memory leak, but I *think* it wouldn't also work on Rust's native wasm backend - when the `grow_memory` wasm instruction is called the memory buffer exported from the wasm module is effectively zeroed, which would invalidate this array.

Probably the best we can do is to expose already existing unsafe `into_typed_array_no_copy`. (Unless someone can figure out another way in which we could actually safely do what is proposed in this issue.)

**Comment by spease** [comment]
How do both of those issues not affect the TypedArray returned by into_typed_array_no_copy? Or is it presumed that they do, but not expected that the TypedArray will live long enough for it to matter?

Either way, it's currently unclear to me how to use that function safely right now, but it looks like what one would want to use for providing large quantities of float data to charts.

**Comment by koute** [comment]
Take a look at the `UnsafeTypedArray` which I've added recently which allows you to pass slices to JavaScript at no cost.

**Comment by koute** [comment]
Since I don't think this can be improved any further now - closing. If you have any further ideas please open up a new issue.
