### ISSUE TITLE
Implement Console API

### ISSUE THREAD

**Issue by DenisKolodin** [koute/stdweb#55]
We discussed [here](https://github.com/DenisKolodin/yew/pull/39) that it's useful to have [Console](https://developer.mozilla.org/en-US/docs/Web/API/Console) methods in this crate to prevent duplication and make it reusable for other crates.

https://github.com/DenisKolodin/yew/pull/39

**Comment by carlosdp** [comment]
would also be cool if we added a `log::Logger` implementation for the `log` crate. I did this in one of my projects and it was really easy, should be even easier with stdweb.

**Comment by koute** [comment]
@carlosdp Hmm... that might actually not be a bad idea, but how would you set the logging level? (e.g. in case of the `env_logger` which everyone uses you can set the `RUST_LOG` environment variable, but you obviously can't do the same on the Web)

**Comment by RangerMauve** [comment]
@koute On the web, the popular module [debug](https://www.npmjs.com/package/debug) uses `localStorage.DEBUG` as the log level. Maybe it would make sense to use `localStorage.RUST_LOG` from the JS side to set the level?

**Comment by carlosdp** [comment]
You could also just say the log level has to be specified at compile-time in your Cargo.toml, where you could have different levels based on your target (debug/release/etc.). I believe that convention is supported by `log`.

**Comment by mredlek** [comment]
I used the following macro to make my life easier when printing console messages:

```rust
macro_rules! consolelog {
    () => ( js! { console.log( "" ); });
    ($fmt:expr) => ( { let msg = format!($fmt); js! { console.log(@{msg}); } });
    ($fmt:expr, $($arg:tt)*) => ( { let msg = format!($fmt, $($arg)*); js! { console.log(@{msg}); } });
}
```

**Comment by hobofan** [comment]
I've published a crude `log` implementation for `stdweb` here: https://github.com/hobofan/stdweb_logger

It's published under a namespaced crate name `hobofan_stdweb_logger` for now, so in case anyone wants to make a more serious attempt, `stdweb_logger` is still available.

Definitely not perfect, but a nice crutch for now!
