### ISSUE TITLE
Drag and Drop API

### ISSUE THREAD

**Issue by gmorenz** [koute/stdweb#56]
I want to use the [HTML Drag and Drop API](https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API). I'm guessing that like [geolocation](https://github.com/koute/stdweb/issues/34) this just needs an implementation added.

I think to do this I need to implement

 - [`DragEvent`](https://developer.mozilla.org/en-US/docs/Web/API/DragEvent), it should sit under `MouseEvent` the same way `MouseEvent` sits under `UIEvent`.
 - [`drag`](https://developer.mozilla.org/en-US/docs/Web/Events/drag), [`dragend`](https://developer.mozilla.org/en-US/docs/Web/Events/dragend), [`dragenter`](https://developer.mozilla.org/en-US/docs/Web/Events/dragenter), [`dragexit`](https://developer.mozilla.org/en-US/docs/Web/Events/dragexit), [`dragleave`](https://developer.mozilla.org/en-US/docs/Web/Events/dragleave), [`dragover`](https://developer.mozilla.org/en-US/docs/Web/Events/dragover), [`dragstart`](https://developer.mozilla.org/en-US/docs/Web/Events/dragstart), and [`drop`](https://developer.mozilla.org/en-US/docs/Web/Events/dragstart) as `ConcreteEvent`s like `ClickEvent` is.
 - [DataTransfer](https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer), [DataTransferItem](https://developer.mozilla.org/en-US/docs/Web/API/DataTransferItem), and [DataTransferItemList](https://developer.mozilla.org/en-US/docs/Web/API/DataTransferItemList) in a way reasonably similar to `FileList`.

Is this all correct and would a pull request be welcome? If so I will start working on it.

**Comment by koute** [comment]
Yep. Pull requests are very welcome! (:

**Comment by gmorenz** [comment]
Awesome, thanks for the prompt response

**Comment by gmorenz** [comment]
The [`DragEvent`](https://developer.mozilla.org/en-US/docs/Web/API/DragEvent) struct and the [`drag`](https://developer.mozilla.org/en-US/docs/Web/Events/drag) event struct seem like they should both be called `DragEvent` in the current naming convention.

How should I name them? Currently I've called the `drag` version `ConcreteDragEvent` but that doesn't seem at all elegant or obvious.

**Comment by koute** [comment]
We already have a precedent for such a situation. We have the `focus` event which is called `FocusEvent`, and the concrete type for the `IFocusEvent` interface is called `FocusRelatedEvent`.

**Comment by gmorenz** [comment]
Great, I'll copy that then :)

**Comment by spease** [comment]
Is there any significant progress on this?

**Comment by teovoinea** [comment]
@spease There’s no PR for it and looking through the user’s repos I can’t seem to find a stdweb fork for it so my guess would be no.

**Comment by gmorenz** [comment]
Nothing very substantial, other things took priority sooner than expected and this didn't get done.

If someone wants I could push what I've done, but you wouldn't be far worse off starting from scratch. Otherwise I'll hopefully come back to this sometime in the next month.
