### ISSUE TITLE
call a FnOnce closure in js

### ISSUE THREAD

**Issue by gliheng** [koute/stdweb#65]
Hi, I need to call a FnOnce closure in js. Basicly, I used a oneshot future from futures library, and I need to move the transmiter to js side.

It looks like in the current implementation I can't do that. Here's a small useless demo.

```rust
use std::mem;
fn main() {
    stdweb::initialize();
    let v = vec![1, 2, 3];
    let call = move || {
        mem::drop(v);
    };
    js! {
        let call = @{call};
        call();
    }
    stdweb::event_loop();
}
```

This compiles with error:
expected a closure that implements the `FnMut` trait, but this closure only implements `FnOnce`

Any idea, I can make this happen?

**Comment by CryZe** [comment]
You can wrap it in an Option and then call .take() on it, like here: https://github.com/CryZe/stdweb-io/blob/9f86196db37e70e5c53567482247b55806d3d779/src/timeout.rs#L23-L29

**Comment by koute** [comment]
Since `0.3` there is also the [`Once` wrapper](https://docs.rs/stdweb/0.3.0/stdweb/struct.Once.html) with which you can directly pass `FnOnce` closures to the `js!` macro; if you change `@{call}` into `@{Once(call)}` your example will compile.

**Comment by gliheng** [comment]
Tried both approach and worked smoothly. and thank you for the new Once wrapper. It's very convenient. I'll close this issue now.
