### ISSUE TITLE
Road to `0.4.0`

### ISSUE THREAD

**Issue by koute** [koute/stdweb#75]
* [X] (breaking change) Get rid of every `usize` from `src/webapi`.
* [X] (breaking change) Rename `KeydownEvent` into `KeyDownEvent`, `KeyupEvent` into `KeyUpEvent` and `Keypress` into `KeyPressEvent` to be consistent with the mouse events.
* [X] (breaking change) Go through all of our bindings, see which ones can fail in the specs, and add appropriate `Result<_, _>` return types.
* [X] (breaking change) Rename every `ReadyState` to something unique.
* [X] (breaking change) Support declarative exports using a procedural macro instead of assigning to `Module.exports on `wasm32-unknown-unknown`.
* [X] Add a link to the actual specs for everything we have bindings for.
* [X] Split `event.rs` into multiple files (https://github.com/koute/stdweb/issues/58)
* [X] Merge `DOMException` (https://github.com/koute/stdweb/pull/89)
* [X] Get rid of `xml_http_request` namespace.
* [X] Add a proper changelog to README.
* [X] Make sure every example works.
* [ ] Update the examples in the README.

In general I'd like to minimize the amount of breaking changes we do, so it'd be nice to get as many of them out of the way as soon as possible, especially the cleanup-y ones.

**Comment by ctjhoa** [comment]
@koute as the `0.4.0` is released, can we close this issue?

**Comment by koute** [comment]
Ah, yes. Thanks for reminding me!
