### ISSUE TITLE
[ERROR] Cannot set property 'STDWEB' of undefined

### ISSUE THREAD

**Issue by Pauan** [koute/stdweb#95]
When using the latest `master` I get this runtime error when running the `todomvc` example:

```
Uncaught TypeError: Cannot set property 'STDWEB' of undefined
    at http://[::1]:8000/js/app.js:1
(anonymous) @ http://[::1]:8000/js/app.js:1
```

This also happens with my own code, and it happens with any target. When I look at the code, I see this:

```js
Module.STDWEB={};Module.STDWEB.to_utf8=... // bunch of code omitted
```

So it's assigning to the `Module` property, but obviously `Module` doesn't exist.

**Comment by koute** [comment]
For which target you're compiling and what version of `cargo-web` are you using?

**Comment by Pauan** [comment]
@koute `cargo-web 0.6.1`

The `asmjs-unknown-emscripten` target demonstrates the problem, but `wasm32-unknown-unknown` works fine. It seems to be an emscripten problem specifically.

Here is the reproduction steps:

1. `cd examples/todomvc`
2. `cargo web start --target asmjs-unknown-emscripten`
3. Open `http://[::1]:8000` in a browser and check the browser's console.

It's probably because the `Module` variable is normally defined in the `index.html` file, but in the case of `todomvc` it uses a custom `index.html` which doesn't define `Module`.

In my opinion the `Module` declaration should be put into the `.js` file, not the `index.html` file.

**Comment by koute** [comment]
The `Module` **is** defined in the `.js` file! By Emscripten itself, in fact. So it's *really* strange that it doesn't work for you, as it does for me. (And it also works on Travis.)

You're using a separately installed Emscripten, right? Which version? Can you also upload the `.js` file generated from the `todomvc` example somewhere so that I can take a look?

**Comment by Pauan** [comment]
> The Module is defined in the .js file! By Emscripten itself, in fact.

I'm not sure if that's true. The [Emscripten documentation](https://kripken.github.io/emscripten-site/docs/api_reference/module.html#creating-the-module-object) says that it's up to the user to define the `Module` object.

> (And it also works on Travis.)

Does Travis do run-time unit tests to verify the behavior of the `todomvc` example? Just to be clear: I'm not talking about a *build failure*, I'm talking about a run-time failure in the browser.

> You're using a separately installed Emscripten, right? Which version?

```
emcc (Emscripten gcc/clang-like replacement) 1.37.16 ()
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

It seems reasonably up to date (released around 2017-07-25), though it's obviously not the latest version.

> Can you also upload the .js file generated from the todomvc example somewhere so that I can take a look?

https://gist.github.com/Pauan/0c16c3454b5d5e06c97814d7334ead26

**Comment by koute** [comment]
> Does Travis do run-time unit tests to verify the behavior of the todomvc example? Just to be clear: I'm not talking about a build failure, I'm talking about a run-time failure in the browser.

It doesn't run the `todomvc` specifically, but yes, it runs all of `stdweb`'s unit tests in a headless Chromium on both Emscripten targets.

Anyhow, yep. It looks like your Emscripten is too old.

Recently I've moved the initialization code from `stdweb::initialize` to having Emscripten prepend it to the final `.js`. This way the library is automatically initialized without having to call `stdweb::initialize`.

It looks like the old version of Emscripten you're using prepends the code **before** it defines `Module` while new versions of Emscripten prepend the code **after**. Looks like it was done in [this commit](https://github.com/kripken/emscripten/pull/5751/commits/45ced441cfecde764ce4e4747527a12a0a624c93)

**Comment by Pauan** [comment]
> It looks like your Emscripten is too old.

I see, I guess I'll need to wait for NixOS to upgrade its version of Emscripten. Thanks for looking into this.
